Disable forks for PR resource
greenplum-db/pxf pull request #1001
Opened 2023-07-14 21:55 UTC by hpandeycodeit

2023-07-17 18:32 UTC, ashuka24 reviewed
Does this also need to be added to the PR pipeline?

2023-07-17 19:15 UTC, bradfordb-vmware requested changes

2023-07-17 19:15 UTC, bradfordb-vmware commented on concourse/pipelines/templates/build_pipeline-tpl.yml
> +    disable_forks: true
This configuration doesn't apply to this Concourse resource; it applys to [telia-oss/github-pr-resource](https://github.com/telia-oss/github-pr-resource).

2023-07-17 19:28 UTC, hpandeycodeit commented
@ashuka24 @bradfordb-vmware added it to the correct file. Thanks for pointing it out!

2023-07-18 20:14 UTC, bradfordb-vmware approved these changes

2023-07-18 22:02 UTC, merged