Updated certification pipeline to include GPDB 7 tests
greenplum-db/pxf pull request #1011
Opened 2023-08-03 20:10 UTC by hpandeycodeit

2023-08-04 22:34 UTC, ashuka24 commented on concourse/pipelines/certification_pipeline.yml
> +        :ci-fail: <((ud/pxf/secrets/ud-concourse-url))/builds/$BUILD_ID|$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME> has failed (<((ud/pxf/common/slack-em-id.id1))>, <((ud/pxf/common/slack-em-id.id1))>)
shouldn't this be `id1` and `id2`?
```suggestion
        :ci-fail: <((ud/pxf/secrets/ud-concourse-url))/builds/$BUILD_ID|$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME> has failed (<((ud/pxf/common/slack-em-id.id1))>, <((ud/pxf/common/slack-em-id.id2))>)

2023-08-07 20:16 UTC, edespino requested changes
Review comments left. I will discuss these with engineer.

2023-08-07 20:16 UTC, edespino commented on concourse/pipelines/certification_pipeline.yml
> +        :ci-fail: <((ud/pxf/secrets/ud-concourse-url))/builds/$BUILD_ID|$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME> has failed (<((ud/pxf/common/slack-em-id.id1))>, <((ud/pxf/common/slack-em-id.id2))>)
Also, while we are modifying this line, we can change the following and remove the vault variable.:

((ud/pxf/secrets/ud-concourse-url)) --> ${ATC_EXTERNAL_URL}

2023-08-07 20:16 UTC, edespino commented on concourse/scripts/test.bash
> +	#TODO Revisit this code once the Tinc is removed and pg_regress is implemented. We then no longer need this extra PYTHONPATH setting.
Change the wording slightly:

`#TODO: remove this "if" block once Tinc is replaced with pg_regress.`

2023-08-07 23:27 UTC, edespino approved these changes
Thank you for the discussion and applying the chnages.

2023-08-08 00:13 UTC, ashuka24 approved these changes

2023-08-08 00:22 UTC, yimingli-vmware commented on concourse/pipelines/certification_pipeline.yml
> +- name: Reporting Gate for PXF-GP7
the indentation of this block seems not correct

2023-08-08 00:22 UTC, yimingli-vmware commented on concourse/pipelines/certification_pipeline.yml
> +- name: Certify GPDB-7 with PXF-GP7 on RHEL8
the indentation of this block seems not correct

2023-08-08 15:56 UTC, bradfordb-vmware commented on concourse/pipelines/certification_pipeline.yml
> +- name: Certify GPDB-7 with PXF-GP7 on RHEL8
@hpandeycodeit There is a Make-target in the `concourse/` Makefile for running yamllint that you can run to check for consistent styling of YAML.

2023-08-08 19:03 UTC, yimingli-vmware approved these changes

2023-08-08 21:13 UTC, denalex commented on concourse/pipelines/certification_pipeline.yml
> +      text: ":ci-fail: <${ATC_EXTERNAL_URL}/builds/$BUILD_ID|$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME> has failed (((ud/common/slack-em-ids)))"
why did we remove the positive notification ? I find it useful, indicating a new commit went through the build pipeline

2023-08-08 21:13 UTC, denalex commented on concourse/pipelines/certification_pipeline.yml
> +    regexp: server/published/main/server-rc-7.(.*)-el8_x86_64.tar.gz
wonder why Releng is not publishing this into `server/published/gpdb7/` and into `server/published/main/` instead

2023-08-08 21:13 UTC, denalex commented on concourse/pipelines/certification_pipeline.yml
> +        GP_VER: 6
```suggestion
        GP_VER: 7
```
if only for consistency

2023-08-08 21:36 UTC, hpandeycodeit commented on concourse/pipelines/certification_pipeline.yml
> +    regexp: server/published/main/server-rc-7.(.*)-el8_x86_64.tar.gz
Asked this in releng channel.

2023-08-08 21:37 UTC, hpandeycodeit commented on concourse/pipelines/certification_pipeline.yml
> +      text: ":ci-fail: <${ATC_EXTERNAL_URL}/builds/$BUILD_ID|$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME> has failed (((ud/common/slack-em-ids)))"
As discussed, we are keeping it like this for now and if needed we will change it in future.

2023-08-08 21:39 UTC, bradfordb-vmware commented on concourse/pipelines/certification_pipeline.yml
> +      text: ":ci-fail: <${ATC_EXTERNAL_URL}/builds/$BUILD_ID|$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME> has failed (((ud/common/slack-em-ids)))"
This is the certification pipeline and not the build pipeline -- its triggered on new server release candidates and not commits to PXF. We generally assume that GPDB isn't breaking ABI so its more important to see failures than to see success.

2023-08-08 21:44 UTC, merged