added WASBS test job to dev CI
greenplum-db/pxf pull request #1026
Opened 2023-09-07 17:34 UTC by denalex

This PR adds an optional test job to the dev pipeline. The test job runs `hcfs` automation test suite against Azure Blob Storage (WASB).

2023-09-07 22:36 UTC, bradfordb-vmware approved these changes

2023-09-07 23:55 UTC, edespino commented
I also noticed the `test.yml` file does not list the `WASB_ACCOUNT_NAME` nor `WASB_ACCOUNT_KEY` as params. And similarly, I noticed the `ADL_*` params are also not listed.

2023-09-08 00:01 UTC, edespino commented
I noticed there are uses of `wasbs` and `WASBS`. Yet, there are uses of `WASB` in `WASB_ACCOUNT_NAME` and `ud/pxf/common/wasb-account-name`. For consistency sake, is it possible to use either `wasb` or `wasbs` and not a mix?

2023-09-08 00:04 UTC, edespino requested changes
I noticed there are uses of `wasbs` and `WASBS`. Yet, there are uses of `WASB` in `WASB_ACCOUNT_NAME` and `ud/pxf/common/wasb-account-name`. For consistency sake, is it possible to use either `wasb` or `wasbs` and not a mix?

2023-09-08 16:59 UTC, denalex commented
WASBS to WASB is the same as HTTPS to HTTP -- a protocol variance allowing secure transfer by using TLS. 

So account / credential names are `wasb` while protocol / job names are `wasbs` since we are using secure transfer.

2023-09-08 16:59 UTC, denalex commented on concourse/pipelines/templates/dev_build_pipeline-tpl.yml
> +    - get: gpdb[[gp_ver]]-pxf-dev-centos7-image
I don't know the reason, perhaps they should have this dependency. But I followed the existing pattern for this PR. If we want to change the pattern, we should do it across all the jobs in a separate PR, or better yet merge dev and build pipeline definitions.

2023-09-08 18:44 UTC, edespino commented
To be consistent with other SECURE jobs and using WASB (Windows Azure Storage Blob), how about the following:

Rename:
`Test PXF-GP[[gp_ver]]-WASBS-NO-IMPERS on RHEL7`
to
`Test PXF-GP[[gp_ver]]-WASB-SECURE-NO-IMPERS on RHEL7`

The protocol used (`PROTOCOL: wasbs`) drives the configuration.

2023-09-08 19:36 UTC, edespino commented on concourse/pipelines/templates/dev_build_pipeline-tpl.yml
> +    - get: gpdb[[gp_ver]]-pxf-dev-centos7-image
@denalex I figured as much. It stood out like a sore thumb when I spun up the dev pipeline with only the WASBS config. For now, let's leave this alone. We can consider another PR to fix this or better yet, merge or find alternate mechanism to bring consistency between dev and build pipeline definitions.

2023-09-11 23:13 UTC, edespino commented
There is no need to introduce SECURE into the WASB test job names. The SECURE portion of the name indicates the job is connecting to a Kerberized Hadoop Cluster. Thanks for context @denalex

2023-09-11 23:13 UTC, edespino approved these changes
+1 Thank you for incorporating my review comment.

2023-09-11 23:15 UTC, merged