Templating Pipeline Jobs
greenplum-db/pxf pull request #1043
Opened 2023-10-19 20:45 UTC by hpandeycodeit

- Added build and test template files.
- Added a dictionary that contains the configuration to generate the jobs.
- Renamed jobs to reflect the platform.
- The build and test jobs ( sanity test) jobs are now generated through the templates.

2023-10-19 21:15 UTC, edespino commented on concourse/pipelines/templates/jobs/test-tpl.yml
As there are many test jobs for which this template does not apply, consider changing the name of this template to reflect the type of test (e.g. sanity-test-tpl.yml). I have always thought of the first test column as a sanity test. I will leave it to you to identify the proper name.

2023-10-19 21:16 UTC, edespino commented on concourse/pipelines/templates/jobs/test-tpl.yml
> +## Template for generating test jobs in the dev and build pipeline
If you do update the this test template name, consider updating line one here (again to easily allow an engineer to identify the use of the template.

2023-10-19 21:19 UTC, edespino requested changes
The only change I see is the renaming of the test template file and comment in the corresponding test template. It will help to clearly identify what series of tests the test template applies to. Thanks.

2023-10-20 17:17 UTC, edespino approved these changes
Upon further discussion, at this point there is no need to rename the test files

2023-10-20 17:18 UTC, edespino approved these changes

2023-10-20 19:37 UTC, denalex commented on concourse/pipelines/templates/dev_build_pipeline-tpl.yml
> +##   execution_os: OS platform in which build and test jobs are executed
```suggestion
##   test_os: OS platform in which test jobs are executed
```
it seems this is only for testing, no ? build is done in` build_os` ?

2023-10-20 19:37 UTC, denalex commented on concourse/pipelines/templates/dev_build_pipeline-tpl.yml
> +    {'gp_ver': '5', 'execution_os': 'centos', 'os_ver': '7',  'build_os': 'centos'},
```suggestion
    {'gp_ver': '5', 'build_os': 'centos', 'test_os': 'centos', 'os_ver': '7'},
```
can we have this logical order ?

2023-10-20 19:37 UTC, denalex commented on concourse/pipelines/templates/dev_build_pipeline-tpl.yml
> +    {% set build_platform_ver = build_platform ~ os_ver %}
I am confused with conventions, especially `platform` and `platform_ver`.

It started nicely with `os` meaning the name of OS and `os_ver` meaning the version of the OS. What is the `platform` then ? I could understand if `platform` would be `os` + `os_ver`, but then there is `platform_ver`. Too complex for a developer to understand which one to use.

2023-10-20 19:37 UTC, denalex commented on concourse/pipelines/templates/dev_build_pipeline-tpl.yml
> +    {% else %}
does this section also apply to OEL ?

2023-10-20 19:37 UTC, denalex commented on concourse/pipelines/templates/dev_build_pipeline-tpl.yml
> +      {% set gpdb_os_platform = 'rhel' %}
what is gpdb_os_platform ? the OS the GPDB RPM is built for ?

2023-10-20 20:59 UTC, bradfordb-vmware commented on concourse/pipelines/templates/dev_build_pipeline-tpl.yml
> +    {% set gp_ver = config.gp_ver %}
Is there a reason for doing `{% set gp_ver = config.gp_ver %}`? Could we not just use `config.gp_ver`?

2023-10-20 20:59 UTC, bradfordb-vmware commented on concourse/pipelines/templates/dev_build_pipeline-tpl.yml
> +    {% else %}
It might be clearer if we wrote

```
{% elif platform in ['centos', 'oel', 'rocky'] %}
```

so that it is clear that it does apply to OEL. However, we'd probably want to add in an `{% else %}` which raises an error message for unknown values of `platform`; it looks like we can add a `raise` function to the template tool ([StackOverflow](https://stackoverflow.com/a/29262304)). This would end up looking something like

```
{% if platform in ['ubuntu'] %}
...
{% elif platform in ['centos', 'oel', 'rocky'] %}
...
{% else %}
{{ raise("unknown platform") }}
{% endif %}
```

Or we just add a comment `# also applies to OEL`

2023-10-20 20:59 UTC, bradfordb-vmware commented on concourse/pipelines/templates/jobs/build-tpl.yml
> +## Template for generating build jobs in the dev and build pipeline
Can we add a doc comment listing what template variables are expected here?

2023-10-20 20:59 UTC, bradfordb-vmware commented on concourse/pipelines/templates/jobs/test-tpl.yml
> +## Template for generating test jobs in the dev and build pipeline
Can we add a doc comment listing what template variables are expected here?

2023-10-21 00:54 UTC, hpandeycodeit commented on concourse/pipelines/templates/dev_build_pipeline-tpl.yml
> +      {% set gpdb_os_platform = 'rhel' %}
yes. Like `rhel` or `ubuntu`

2023-10-21 00:59 UTC, hpandeycodeit commented on concourse/pipelines/templates/dev_build_pipeline-tpl.yml
> +    {% else %}
For now I have added a comment here. Once we move the logic/matrix to the template_tool, then we can create a similar function which can throw an error.

2023-10-23 17:40 UTC, bradfordb-vmware approved these changes

2023-10-23 18:05 UTC, merged