Rhel9 support
greenplum-db/pxf pull request #1058
Opened 2023-11-29 17:02 UTC by ashuka24

This PR adds build and test jobs to both dev and pxf-build pipelines.

It also adds a GP6 Multinode job for RHEL9 which is configurable for the dev pipeline using MULTINODE_EL9

In order to provide support for EL9, we also have to update the crypto policies in the remote images and removed the use of the xterm terminal in order to run automation.

2023-11-29 18:46 UTC, xinzweb approved these changes
LGTM.

Feel free to separate the commit for the USER and BRANCH in a separate PR.

2023-11-29 22:30 UTC, denalex requested changes
please remove the release notes stuff from this PR and maybe provide a summary in PR description what needs to be changed once GPDB RHEL9 releases.

otherwise looks good.

2023-11-29 22:30 UTC, denalex commented on .github/workflows/create-release-on-tag.yml
> +            - [#1058](https://github.com/greenplum-db/pxf/pull/1058) Add RHEL9 Support
this should be a part of `Bump version to 6.9.0` PR, not this one.

2023-11-29 22:30 UTC, denalex commented on concourse/pipelines/templates/build_pipeline-tpl.yml
> +    {% if x.os_ver == '9' %}
should we put a note here when we need to change this and to what logic ?

2023-11-29 22:30 UTC, denalex commented on concourse/scripts/build.bash
> +# In case we are testing a dev version (i.e: 6.25.3+dev.6.54a3437), GPDB_VERSION%%+* will remove any extra string from + onwards
should this be reversed once the RHEL9 releases since we will nt be testing with dev versions anymore ?

2023-11-29 22:34 UTC, ashuka24 commented on .github/workflows/create-release-on-tag.yml
> +            - [#1058](https://github.com/greenplum-db/pxf/pull/1058) Add RHEL9 Support
That was my mistake. I committed on the wrong branch. I have removed it from this PR.

2023-11-29 22:58 UTC, ashuka24 commented on concourse/scripts/build.bash
> +# In case we are testing a dev version (i.e: 6.25.3+dev.6.54a3437), GPDB_VERSION%%+* will remove any extra string from + onwards
Can we guarantee this? If releases have to be aligned, there is a chance that we have to build against dev versions in the future.

2023-11-30 02:48 UTC, bradfordb-vmware commented on automation/src/main/java/org/greenplum/pxf/automation/components/common/cli/PivotalSshRsa.java
> +		 */
This comment is not correct -- we don't currently test PXF CLI with automation. The color codes were coming from other commands that were terminal-aware. By switching to a "dumb" PTY, those commands don't emit the ANSI escape sequences.

2023-11-30 02:48 UTC, bradfordb-vmware commented on concourse/README.md
> +To deploy multi-node dev pipeline, you can specify either the `MULTINODE_EL7` for EL7, `MULTINODE_EL8` for EL8, `MULTINODE_EL9` for EL9 or
Since we have four options now, I'd switch to a bulleted list:

```
To deploy multi-node dev pipeline, you can specify

* `MULTINODE_EL7=<true|false>` for EL7
* `MULTINODE_EL8=<true|false>` for EL8
* `MULTINODE_EL9=<true|false>` for EL9
* `MULTINODE_NO_IMPERSONATION=<true|false>` for EL7

2023-11-30 02:48 UTC, bradfordb-vmware commented on concourse/pipelines/templates/jobs/test-multinode-tpl.yml
> +    # install_multinode_hadoop.yml. See line 80 and 81 where we try to SCP down the hadoop and hive conf files.
Could we replace `scp` with `rsync` in `install_multinode_hadoop` and avoid the need for special casing here?

2023-11-30 02:48 UTC, bradfordb-vmware commented on concourse/pipelines/templates/resources/greenplum-rocky9-package-tpl.yml
> +    regexp: server/release-candidates/gpdb7/greenplum-db-server-(7.*)-el9-x86_64.rpm
It looks like the only difference between GP6 and GP7 is `maintenance` vs `server` -- could we have a variable `path_prefix` that we set depending on `gp_ver` and then just have one resource definition?

2023-11-30 02:48 UTC, bradfordb-vmware commented on concourse/scripts/build.bash
> +        fi
```suggestion
        . /etc/os-release
        
        case "${VERSION_ID}" in
        9.*) gpdb_file_name="greenplum-db-server" ;;
        7.*|8.*) gpdb_file_name="greenplum-db" ;;
        *)
            echo >&2 "unknown value for VERSION_ID: ${VERSION_ID}"
            exit 1
            ;;
        esac
```

2023-11-30 02:48 UTC, bradfordb-vmware commented on concourse/scripts/build.bash
> +        pkg_file=$(find "${GPDB_PKG_DIR}" -name "${gpdb_file_name}-${GPDB_VERSION}-${DISTRO_MATCHING_PATTERN}*-x86_64.rpm")
It turns out that `find` has `-regex` option for matching file names if we wanted to match `greenplum-db-x.y.z` and `greenplum-db-server-x.y.z`, we could do

```sh
find . -regextype egrep -regex './greenplum-db(-server)?.*.rpm'
```

Or we should just do

```sh
find . -name 'greenplum-db-server-${GPDB_VERSION}-${DISTRO_MATCHING_PATTERN}*-x86_64.rpm' -o -name 'greenplum-db-${GPDB_VERSION}-${DISTRO_MATCHING_PATTERN}*-x86_64.rpm'
```

2023-11-30 02:48 UTC, bradfordb-vmware commented on concourse/scripts/build.bash
> +# In case we are testing a dev version (i.e: 6.25.3+dev.6.54a3437), GPDB_VERSION%%+* will remove any extra string from + onwards
I don't know if we can guarantee it but if that becomes the norm, then I'd want to explore a less "hacky" approach. But that would require us to understand more deeply

* Why can't our CI scripts just use the `/usr/local/greenplum-db` symbolic link?
* Why is there a mismatch between GPDB's version inside of the RPM versus the version in the filename?

I'm in favor of leaving a `TODO` to revert this once GPDB EL9 support is GA across 6 and 7.

2023-11-30 02:48 UTC, bradfordb-vmware commented on concourse/scripts/pxf_common.bash
> +	# in case of dev builds, get simplified version from the version file
Can we use a bash regex match instead of reading the version from the Concourse resource created `version` file?

2023-11-30 02:48 UTC, bradfordb-vmware commented on concourse/scripts/test_pxf_multinode.bash
> +			echo "Failed to update crypto policy or restart SSH. Please check the logs for more information."
If we fail to update the crypto policy, should we bail? It seems like this error message would just get lost in all the other CI output. Would we even know/think to search for this?
```suggestion
			echo >&2 "Failed to update crypto policy or restart SSH. Please check the logs for more information."
			exit 1
```

2023-12-01 01:13 UTC, ashuka24 commented on automation/src/main/java/org/greenplum/pxf/automation/components/common/cli/PivotalSshRsa.java
> +		 */
I have updated this block, please take a second look

2023-12-01 18:45 UTC, ashuka24 commented on concourse/pipelines/templates/build_pipeline-tpl.yml
> +    {% if x.os_ver == '9' %}
i have added a comment

2023-12-01 18:46 UTC, ashuka24 commented on concourse/pipelines/templates/resources/greenplum-rocky9-package-tpl.yml
> +    regexp: server/release-candidates/gpdb7/greenplum-db-server-(7.*)-el9-x86_64.rpm
As this is a temporary template and should be removed once we can pull rocky9 rpms from pivnet, I will leave this as is...

2023-12-02 00:43 UTC, ashuka24 commented on concourse/scripts/pxf_common.bash
> +	# in case of dev builds, get simplified version from the version file
We use the `version` provided by the Concourse resource in various other scripts as well. I think for this PR, it is fine to be consistent across scripts.

2023-12-04 19:00 UTC, yimingli-vmware approved these changes

2023-12-04 19:00 UTC, yimingli-vmware commented on concourse/scripts/install_multinode_hadoop.bash
> +rsync "${hadoop_namenode_1}:${HADOOP_PREFIX}/etc/hadoop/*-site.xml" ipa_env_files/conf/
can we add come context here why we need to replace `scp` with this `rsync`?

2023-12-04 19:00 UTC, yimingli-vmware commented on concourse/scripts/pxf_common.bash
> +	gpdb_version=$(<"${gpdb_package}/version")
we need the full version name only for the dev builds?

2023-12-04 22:16 UTC, ashuka24 commented on concourse/scripts/install_multinode_hadoop.bash
> +rsync "${hadoop_namenode_1}:${HADOOP_PREFIX}/etc/hadoop/*-site.xml" ipa_env_files/conf/
we switched to rsync because scp is deprecated in rocky9 and was causing issues. After taking a second look, we can overcome this by pulling down the remote variables before running scp as it is only remote variable expansion that is no longer available

2023-12-04 22:22 UTC, ashuka24 commented on concourse/scripts/pxf_common.bash
> +	gpdb_version=$(<"${gpdb_package}/version")
i have moved this variable to where it is being used so hopefully it will be more clear.

2023-12-04 23:37 UTC, merged