docs - rhel9 support, updating os upgrade topic
greenplum-db/pxf pull request #1061
Opened 2023-12-07 00:15 UTC by ashuka24

updates for pxf: 
- add rhe9 supported platform into intro topic
- updating the 'pxf considerations when upgrading os' topic

2023-12-07 16:46 UTC, bradfordb-vmware commented on docs/content/upgrade_os.html.md.erb
> +1. Upgrade PXF in your current cluster to at least the version of PXF that first supports the desired platform. (e.g if you want to upgrade to RHEL 8, upgrade to PXF v6.3+) and verify PXF operation *
The current set of docs do not make use of `e.g.`.  I would rewrite this with `For example`:

> Upgrade PXF in your current cluster to at least the version of PXF list in the table above and verify PXF operation with that version **before** you commence the OS upgrade. For example: If you want to upgrade your Greenplum 6 cluster to RHEL8, upgrade PXF to v6.3+.

2023-12-07 16:46 UTC, bradfordb-vmware commented on docs/content/upgrade_os.html.md.erb
> +| RHEL 9.x | 6.9+ for Greenplum 6.26+  |
```suggestion
| OS Version | PXF Version               |
|------------|---------------------------|
| RHEL 8.x   | 6.3+ for Greenplum 6.20+  |
| RHEL 8.x   | 6.8+ for Greenplum 7.x    |
| RHEL 9.x   | 6.9+ for Greenplum 6.26+  |
```

Since its a new table, can we align the vertical pipes?

2023-12-07 16:46 UTC, bradfordb-vmware commented on docs/content/upgrade_os.html.md.erb
> +1. Download a PXF package for the upgraded OS (e.g PXF v6.3+ for RHEL 8) from [VMware Tanzu Network](https://network.tanzu.vmware.com/products/vmware-greenplum/). *You must download the same version
```suggestion
1. Download a PXF package for the upgraded OS from [VMware Tanzu Network](https://network.tanzu.vmware.com/products/vmware-greenplum/). *You must download the same version of PXF as that was running on the original Greenplum Database cluster.*
```

Note: when using the abbreviation for 'for example', it should be written as `e.g.` since it is short for the Latin phrase 'exempli gratia' and it is generally followed by a comma since it is taking the place of 'for example'

2023-12-07 18:05 UTC, VMWareJennyBeth commented on docs/content/upgrade_os.html.md.erb
> +1. Upgrade PXF in your current cluster to at least the version of PXF that first supports the desired platform. (e.g if you want to upgrade to RHEL 8, upgrade to PXF v6.3+) and verify PXF operation *
For example: If ==> For example, if

2023-12-07 18:06 UTC, VMWareJennyBeth commented on docs/content/upgrade_os.html.md.erb
> +1. Download a PXF package for the upgraded OS (e.g PXF v6.3+ for RHEL 8) from [VMware Tanzu Network](https://network.tanzu.vmware.com/products/vmware-greenplum/). *You must download the same version
We don't use abbreviations in our docs.

For example, not e.g.

That is, not i.e.

2023-12-07 18:06 UTC, VMWareJennyBeth requested changes
Very minor comments, otherwise great.

2023-12-07 22:42 UTC, yimingli-vmware approved these changes

2023-12-08 17:34 UTC, VMWareJennyBeth commented on docs/content/upgrade_os.html.md.erb
> +If you plan to upgrade the operating system in your Greenplum Database cluster hosts to a new OS and you are running PXF in your Greenplum installation, please refer to the above table to determine w
determine what => determine which

2023-12-12 19:10 UTC, merged