docs - init/reset changes, deprecation; register
greenplum-db/pxf pull request #502
Opened 2020-11-19 22:16 UTC by lisakowen

changes related to initialization and reset deprecation;  in this PR:
- remove init/reset topic
- in most cases, change initialize -> configure
- ref page init/reset commands - update descriptions, deprecate
- pxf [cluster] register - now copies only control file

doc review site links:
- pxf ref page:  http://docs-lisa-pxf6-review.cfapps.io/pxf/6-0/using/ref/pxf.html
- pxf cluster ref page:  http://docs-lisa-pxf6-review.cfapps.io/pxf/6-0/using/ref/pxf-cluster.html

2020-11-19 22:20 UTC, lisakowen commented
i didn't think there were any upgrade implications to these changes, let me know if i missed something.

2020-11-23 14:35 UTC, frankgh approved these changes

2020-12-01 19:28 UTC, ashuka24 approved these changes

2021-01-05 21:46 UTC, dyozie requested changes

2021-01-05 21:46 UTC, dyozie commented on docs/content/ref/pxf.html.md.erb
> +- Synchronize the PXF configuration from the master to the standby master or a segment hosts.
hosts -> host

2021-01-05 21:46 UTC, dyozie commented on docs/content/instcfg_pxf.html.md.erb
> +2. Register the PXF Extension with Greenplum Database (see [pxf cluster register](ref/pxf-cluster.html)). Run this command after your first installation of a PXF version 6.x, and/or after you upgrade
Extension -> extension

2021-01-05 21:59 UTC, dyozie approved these changes

2021-01-07 18:45 UTC, merged