docs - pxf v6 new config and config changes
greenplum-db/pxf pull request #528
Opened 2021-01-14 22:22 UTC by lisakowen

document the new pxf v6 config and config changes.  in this PR:
- content for new topic "about t he pxf configuration files"
- calling out some advanced config topics (agent host/port, logging, memory/thread, fragment caching) in a new "Advanced Configuration" left nav entry.  moved and updated some content from troubleshooting guide.
- update content about configuring logging, memory/threads, and fragment caching to specify new config files
- update "registering library dependencies" topic to refer to new pxf-env.sh PXF_LOADER_PATH, LD_LIBRARY_PATH
- add misc xrefs to some new/existing topics

NOT IN THIS PR:  migration/upgrade considerations for config settings

doc review site links:
- new "about pxf config files" page - http://docs-lisa-pxf6-cfg.cfapps.io/pxf/6-0/using/config_files.html
- registering jar dependencies page - http://docs-lisa-pxf6-cfg.cfapps.io/pxf/6-0/using/reg_jar_depend.html
- logging config page - http://docs-lisa-pxf6-cfg.cfapps.io/pxf/6-0/using/cfg_logging.html
should be easy enough to navigate to the other pages of interest with those.

2021-01-28 21:09 UTC, lisakowen commented
this PR could use a technical review.

2021-01-29 18:01 UTC, frankgh reviewed
it looks good in general, I added a couple of comments

2021-01-30 00:47 UTC, denalex commented on docs/content/cfg_mem.html.md.erb
> +Because a single PXF agent (JVM) serves multiple segments on a segment host, the PXF heap size can be a limiting runtime factor. This will be more evident under concurrent workloads and/or queries ag
let's consistently call PXF Server or PXF Service (not agent)

2021-01-30 00:47 UTC, denalex commented on docs/content/cfg_mem.html.md.erb
> +If increasing the maximum heap size is not suitable for your Greenplum Database deployment, try decreasing the number of concurrent working threads configured for PXF's underlying Tomcat web applicat
```suggestion
If increasing the maximum heap size is not suitable for your Greenplum Database deployment, try decreasing the number of concurrent working threads configured for PXF's embedded Tomcat web server. A decrease in the number of running threads will prevent any PXF node from exhausting its memory, while ensuring that current queries run to completion (albeit a bit slower). Tomcat's default behavior is to queue requests until a thread is free, or the queue is exhausted.
```

2021-01-30 00:47 UTC, denalex commented on docs/content/cfg_mem.html.md.erb
> +PXF thread capacity is determined by the profile and whether or not the data is compressed. If you plan to run large workloads on a large number of files in an external Hive data store, or you are re
this is a bit confusing, there's no such thing as `thread capacity`. Large workloads require more memory and lower thread count limits concurrency and hence memory consumption.

2021-01-30 00:47 UTC, denalex commented on docs/content/cfg_mem.html.md.erb
> +**Note**: Keep in mind that an increase in the thread count correlates with an increase in memory consumption when the thread count is exhausted.
I am not sure about the last part `...when the thread count is exhausted`. When it is exhausted, our accept count is set to 100 now, so it will queue 100 more requests and then give an HTTP error.

2021-01-30 00:47 UTC, denalex commented on docs/content/config_files.html.md.erb
> +| pxf.task.pool.core-size | The number of core streaming threads. | 8 |
do we need to explain what `core streaming threads` are ?

2021-01-30 00:47 UTC, denalex commented on docs/content/config_files.html.md.erb
> +The `pxf-log4j2.xml` file configures PXF and subcomponent logging. By default, PXF is configured to log at the `warn` or `error` levels and more severe.
when we devs are saying log at INFO level, it means INFO and more severe, so it is INFO, WARN, ERROR, and more severe.

2021-01-30 00:47 UTC, denalex commented on docs/content/config_files.html.md.erb
> +1. (Re)start PXF on each segment host:
```suggestion
1. (Re)start PXF on all segment hosts:
```

2021-01-30 13:28 UTC, frankgh commented on docs/content/config_files.html.md.erb
> +The `pxf-log4j2.xml` file configures PXF and subcomponent logging. By default, PXF is configured to log at the `warn` or `error` levels and more severe.
maybe `to reduce verbosity from third-party libraries`

2021-02-01 17:30 UTC, dyozie requested changes

2021-02-01 21:04 UTC, lisakowen commented on docs/content/cfg_logging.html.md.erb
> +PXF utilizes `log4j2` for service-level logging. PXF service-related log messages are captured in a log file specified by PXF's `log4j2` properties file, `$PXF_BASE/conf/pxf-log4j2.xml`. The default
the current pxf docs identify that the user can change the default log file name, and the property that the user would update to change this is in pxf-log4j.properties:
```
# use the same value directory as set for $PXF_LOGDIR
log4j.appender.ROLLINGFILE.File=${pxf.log.dir}/pxf-service.log
```
in both pxf 5 and 6, the user can specify the location of the log file in PXF_LOGDIR in pxf-env.sh.

in pxf 6, the default log file name property is hidden in the application.properties config file in the uber JAR.  i think that you are asking that we document the logging.file.name property and value default value in pxf 6 - is this correct?  how/can the user change this?  why we wouldn't add the property to change the name of the log file to the pxf-log4j2.xml configuration file? 

which brings me to a related question - why did we choose to change the logging config file from properties format to xml format?  doesn't log4j2 support both?

2021-02-01 21:11 UTC, lisakowen commented on docs/content/cfg_fragcache.html.md.erb
> +PXF fragment metadata caching is enabled by default. To turn off fragment metadata caching, or to re-enable it after turning it off, perform the following procedure:
how about i remove the fragment caching topic from the navigation pane, and we can revisit related content and placement (or lack thereof) when this is fleshed out on the development end?

2021-02-01 21:22 UTC, lisakowen commented on docs/content/cfg_mem.html.md.erb
> +Because a single PXF agent (JVM) serves multiple segments on a segment host, the PXF heap size can be a limiting runtime factor. This will be more evident under concurrent workloads and/or queries ag
good point.  what about "PXF Service"?  then "PXF server" would reference external data store configurations for PXF.

2021-02-03 21:19 UTC, lisakowen commented on docs/content/config_files.html.md.erb
> +| pxf.task.pool.core-size | The number of core streaming threads. | 8 |
will address this later.

2021-02-03 21:20 UTC, lisakowen commented on docs/content/cfg_logging.html.md.erb
> +
will update the docs when logging level or debug logging is exposed via a pxf-env.sh property.

2021-02-03 21:21 UTC, lisakowen commented on docs/content/cfg_fragcache.html.md.erb
> +PXF fragment metadata caching is enabled by default. To turn off fragment metadata caching, or to re-enable it after turning it off, perform the following procedure:
ok.  removed the fragment caching topic, and add a deprecation notice for the property and note the change in the release notes (separate PR).

2021-02-03 21:22 UTC, lisakowen commented on docs/content/cfg_mem.html.md.erb
> +- PXF logs the following messages to XXX`$PXF_BASE/logs/pxf-service.log`XXX on the segment host:
i'll make a note to touch base with you about this in the future, @francisco.

2021-02-03 23:21 UTC, lisakowen commented on docs/content/cfg_logging.html.md.erb
> +PXF utilizes `log4j2` for service-level logging. PXF service-related log messages are captured in a log file specified by PXF's `log4j2` properties file, `$PXF_BASE/conf/pxf-log4j2.xml`. The default
ok.  not documenting how to change the log file name.  added a new topic to the logging page to describe how to configure the PXF log directory:  http://docs-lisa-pxf6-cfg.cfapps.io/pxf/6-0/using/cfg_logging.html#cfglogdir . (repushed the review site, may need to refresh.)

2021-02-04 00:09 UTC, lisakowen commented on docs/content/cfg_mem.html.md.erb
> +Because a single PXF agent (JVM) serves multiple segments on a segment host, the PXF heap size can be a limiting runtime factor. This will be more evident under concurrent workloads and/or queries ag
replaced `PXF agent` references with `PXF Service`

2021-02-04 00:10 UTC, lisakowen commented
i believe that i addressed all of the outstanding comments on this PR.  i also repushed the review site.

2021-02-04 20:02 UTC, denalex commented on docs/content/cfg_logging.html.md.erb
> +PXF utilizes Apache Log4j 2 for service-level logging. PXF Service-related log messages are captured in a log file specified by the PXF Log4j 2 configuration file, `$PXF_BASE/conf/pxf-log4j2.xml`. Th
default log level for PXF code in INFO, here we're saying : "The default PXF logging configuration writes `warn` ..."

2021-02-04 20:02 UTC, denalex approved these changes

2021-02-04 21:45 UTC, frankgh approved these changes

2021-02-04 22:00 UTC, lisakowen commented on docs/content/access_hdfs.html.md.erb
>  2. Invokes the HDFS Java API to request metadata information for the HDFS file from the HDFS NameNode.
thanks, francisco.  i've added a docs "todo" for v6.0.0 to address architectural changes due to springboot integration and now the refactor (content and diagrams).

2021-02-18 01:33 UTC, ashuka24 commented on docs/content/cfg_logging.html.md.erb
> +The default configuration for the PXF Service logs at the `info` and more severe levels, and logs at the `warn` or `error` and more severe levels for some third-party libraries to reduce verbosity. L
This sentence seems a bit confusing, could we rephrase for clarity? 
More severe levels here refers to `fatal` or `error` correct? 

```suggestion
The default configuration for the PXF Service logs at the `info` and more severe levels. For some third-party libraries, the PXF Service logs at the `warn` or `error` and more severe levels to reduce verbosity. Log messages are written to the `$PXF_LOGDIR/pxf-service.log` file. You can change the PXF log directory if you choose.
```

2021-02-18 01:33 UTC, ashuka24 commented on docs/content/cfg_mem.html.md.erb
> +- PXF logs the following messages to XXX`$PXF_BASE/logs/pxf-service.log`XXX on the segment host:
This fix is now in PR: https://github.com/greenplum-db/pxf/pull/557

2021-02-18 15:48 UTC, lisakowen commented on docs/content/cfg_logging.html.md.erb
> +The default configuration for the PXF Service logs at the `info` and more severe levels, and logs at the `warn` or `error` and more severe levels for some third-party libraries to reduce verbosity. L
thanks, ashuka. updated.  and es, more severe refers to fatal or error.

2021-02-18 15:50 UTC, lisakowen commented on docs/content/cfg_mem.html.md.erb
> +- PXF logs the following messages to XXX`$PXF_BASE/logs/pxf-service.log`XXX on the segment host:
thanks, ashuka.  i am going to create a separate docs PR for the OOM logging.  there will likely be updates to a few more pages in the docs, and i'd like to merge this PR.

2021-02-19 16:04 UTC, merged