Docs - added extra steps to Configuration page
greenplum-db/pxf pull request #594
Opened 2021-03-15 22:05 UTC by mperezfuster

Added some extra steps in order to successfully configure PXF for the first time:

- Add instructions on how to configure $JAVA_HOME
- Add explicit command for registering cluster: pxf cluster register
- Add pxf cluster sync before starting PXF
- Referenced to enabling PXF extension for GPDB

Preview: https://mireia-pxf-config.sc2-04-pcf1-apps.oc.vmware.com/pxf/6-0/using/instcfg_pxf.html

2021-03-15 22:21 UTC, ashuka24 commented on docs/content/instcfg_pxf.html.md.erb
> +1. Install Java 8 or 11 on each Greenplum Database host as described in [Installing Java for PXF](install_java.html). Then use the value of `$JAVA_HOME` you identified on Step 4 and add it to the `px
I think that could be made a little more clear here that step 4 refers to the step 4 from the `Installing Java for PXF` page.

2021-03-15 22:21 UTC, ashuka24 commented on docs/content/instcfg_pxf.html.md.erb
> +1. Make sure that the cluster configuration has been synchronized:
add line between bullets here

2021-03-15 22:21 UTC, ashuka24 commented on docs/content/instcfg_pxf.html.md.erb
> +2. Once PXF service has been started, enable the [PXF Greenplum Database extension](using_pxf.html).
same thing, add line between bullets here for consistency

2021-03-16 02:13 UTC, lisakowen requested changes
thanks for pulling this together.  it really fills in some of the gaps for a new-to-pxf user.

2021-03-16 02:13 UTC, lisakowen commented on docs/content/instcfg_pxf.html.md.erb
> +    - Locate the `JAVA_HOME` setting in the `pxf-env.xml` file, and update it with the corresponding path.
pxf-env.xml -> pxf-env.sh
what about something like :  and update it with the corresponding path -> uncomment it if necessary, and set it to your $JAVA_HOME value. For example:

2021-03-16 02:13 UTC, lisakowen commented on docs/content/instcfg_pxf.html.md.erb
> +    [gpadmin@<gpmaster>]$ pxf cluster register
[gpadmin@<gpmaster>]$ -> gpadmin@gpmaster$  (can remove the braces and <>)

2021-03-16 02:13 UTC, lisakowen commented on docs/content/instcfg_pxf.html.md.erb
> +    Installing PXF extension on master host, standby master host, and 2 segment hosts...
we have not typically included command line output in the docs.  if we do, we might want to genericize the messages a little.

2021-03-16 02:13 UTC, lisakowen commented on docs/content/instcfg_pxf.html.md.erb
> +1. Make sure that the cluster configuration has been synchronized:
what about something along the lines of "Synchronize the PXF configuration to all hosts in the cluster"?  it is true that they may have already run this in a previous step.

2021-03-16 02:13 UTC, lisakowen commented on docs/content/instcfg_pxf.html.md.erb
> +    [gpadmin@<gpmaster>]$ pxf cluster sync
same comments about shell prompt and command output.

2021-03-16 02:13 UTC, lisakowen commented on docs/content/instcfg_pxf.html.md.erb
> +2. Once PXF service has been started, enable the [PXF Greenplum Database extension](using_pxf.html).
what if the last step is ".. enable the PXF extension (LINK TO THIS SECTION ON THE PAGE), and grant access to users (LINK TO THIS SECTION ON THE PAGE)

2021-03-16 02:13 UTC, lisakowen commented on docs/content/instcfg_pxf.html.md.erb
> +1. Install Java 8 or 11 on each Greenplum Database host as described in [Installing Java for PXF](install_java.html). Then use the value of `$JAVA_HOME` you identified on Step 4 and add it to the `px
what about rewording this a bit:
Then use the value of `$JAVA_HOME` you identified on Step 4 and add it to the `pxf-env.sh` [configuration file](config_files.html). 

to

You must inform PXF of the $JAVA_HOME setting by specifying its value in the `pxf-env.sh` [configuration file](config_files.html).

2021-03-16 14:50 UTC, mperezfuster commented on docs/content/instcfg_pxf.html.md.erb
> +1. Install Java 8 or 11 on each Greenplum Database host as described in [Installing Java for PXF](install_java.html). Then use the value of `$JAVA_HOME` you identified on Step 4 and add it to the `px
thanks @lisakowen I have changed all these

2021-03-16 16:42 UTC, denalex approved these changes

2021-03-16 17:09 UTC, lisakowen approved these changes

2021-03-16 22:46 UTC, ashuka24 approved these changes

2021-03-16 22:53 UTC, bradfordb-vmware approved these changes
Just some minor wording suggestions, but otherwise it looks good.

2021-03-16 22:53 UTC, bradfordb-vmware commented on docs/content/instcfg_pxf.html.md.erb
> +1. Synchronize the PXF configuration to all hosts in the cluster.
```suggestion
1. After making any configuration changes, synchronize the PXF configuration to all hosts in the cluster.
```

2021-03-16 22:53 UTC, bradfordb-vmware commented on docs/content/instcfg_pxf.html.md.erb
> +1. After you complete PXF configuration, you [Start PXF](cfginitstart_pxf.html).
```suggestion
1. After synchronizing PXF configuration changes, [Start PXF](cfginitstart_pxf.html).
```

2021-03-16 22:53 UTC, bradfordb-vmware commented on docs/content/instcfg_pxf.html.md.erb
> +        export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/
```suggestion
        export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
```

On RHEL 7, `/usr/lib/jvm/java-1.8.0-openjdk` is a symlink that resolves to `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/` so the two paths both work; the full path includes packaging versions that might change over time though.

2021-03-18 15:02 UTC, mperezfuster commented on docs/content/instcfg_pxf.html.md.erb
> +        export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/
actually I had forgotten to add the /jre subdirectory, thanks for the heads up

2021-03-22 19:14 UTC, merged