Docs- Sum up of the directory changes with PXF 6
greenplum-db/pxf pull request #601
Opened 2021-03-22 20:14 UTC by mperezfuster

We want to make clear to users the main differences between the old $PXF_CONF in PXF and the new paths in PXF 6:
Can be previewed here:
https://mireia-pxf-base.sc2-04-pcf1-apps.oc.vmware.com/pxf/6-0/using/about_pxf_dir.html

2021-03-22 23:17 UTC, lisakowen requested changes
this info is really going to be helpful to the user.

2021-03-22 23:17 UTC, lisakowen commented on docs/content/about_pxf_dir.html.md.erb
> +This documentation uses `$PXF_HOME` to refer to the PXF installation directory. Its value depends on how PXF has been installed:
... on how you have installed PXF:

2021-03-22 23:17 UTC, lisakowen commented on docs/content/about_pxf_dir.html.md.erb
> + - If you install PXF as part of Greenplum Database, its value will be `$GPHOME/pxf`.
If you are using the PXF installed with Greenplum Database, its value is $GPHOME/pxf.  (actually, for the pxf 6 version of the docs, this will never be the case unless/until we embed pxf 6 with the server distribution.)

2021-03-22 23:17 UTC, lisakowen commented on docs/content/about_pxf_dir.html.md.erb
> + - If you install the PXF rpm or deb package, its value will be `/usr/local/pxf-gp<greenplum-major-version>`, or the directory of your choosing (CentOS/RHEL only).
install -> installed
code font for rpm and deb
will be -> is

2021-03-22 23:17 UTC, lisakowen commented on docs/content/about_pxf_dir.html.md.erb
> +<div class="note">This documentation uses the <code>$PXF_HOME</code> and <code>$PXF_BASE</code> environment variables to <i>reference</i> the PXF installation and runtime configuration directories. P
can we move this note after the next paragraph, and change slightly to say

This documentation uses the $PXF_HOME environment variable to reference the PXF installation directory. PXF uses this variable internally at runtime; it is not set in your shell environment, and will display as empty if you attempt to echo its value.  Similarly, this documentation uses the $PXF_BASE environment variable to reference the PXF runtime configuration directory.  PXF uses the variable internally.  it will only, and must, be set in your shell environment if you explicitly relocate the directory.

2021-03-22 23:59 UTC, dyozie approved these changes

2021-03-23 14:16 UTC, mperezfuster commented on docs/content/about_pxf_dir.html.md.erb
> + - If you install PXF as part of Greenplum Database, its value will be `$GPHOME/pxf`.
so PXF_HOME will always be /usr/local/pxf-gbX ? In that case we might not need this bullet point list

2021-03-23 23:39 UTC, bradfordb-vmware approved these changes

2021-03-23 23:39 UTC, bradfordb-vmware commented on docs/content/about_pxf_dir.html.md.erb
> +<div class="note">This documentation uses the <code>$PXF_HOME</code> environment variable to reference the PXF installation directory. PXF uses this variable internally at runtime; it is not set in y
There is something awkward about the wording of the last sentence; in particular `only, and must,`. I wonder if this would be a better wording?

> It only needs to be set in your shell environment if you explicitly relocate the directory.

2021-03-24 16:24 UTC, mperezfuster commented on docs/content/about_pxf_dir.html.md.erb
> +<div class="note">This documentation uses the <code>$PXF_HOME</code> environment variable to reference the PXF installation directory. PXF uses this variable internally at runtime; it is not set in y
makes sense, thanks Bradford

2021-03-25 18:42 UTC, merged