Docs - Added Upgrading PXF Step 2
greenplum-db/pxf pull request #602
Opened 2021-03-22 21:23 UTC by mperezfuster

Added Step 2 since it was missing
Also referenced user to the Installation and Configuration Directories to make sure we highlight these changes when upgrading from PXF 5
Preview: https://mireia-pxf-upgrade.sc2-04-pcf1-apps.oc.vmware.com/pxf/6-0/using/upgrade_5_to_6.html

2021-03-22 21:35 UTC, lisakowen requested changes

2021-03-22 21:35 UTC, lisakowen commented on docs/content/upgrade_5_to_6.html.md.erb
>  1. [Install PXF 6.x](installing.html), identify and note the new PXF version number, and then continue your PXF upgrade with [Step 3: Complete the Upgrade to PXF 6.x](#pxfup).
i think we can probably remove this line.

2021-03-22 21:35 UTC, lisakowen commented on docs/content/upgrade_5_to_6.html.md.erb
> +## <a id="pxfinst"></a>Step 2: Install PXF 6.x
Install -> "Installing"

2021-03-22 21:35 UTC, lisakowen commented on docs/content/upgrade_5_to_6.html.md.erb
> +1. Follow the steps outlined in [Install PXF 6.x](../release/installing_pxf.html), and identify and note the new PXF version number.
Install PXF 6.x -> Installing PXF (this is the name of main topic)

2021-03-22 21:35 UTC, lisakowen commented on docs/content/upgrade_5_to_6.html.md.erb
> +1. Check out the new installation layout in [Installation and Configuration Directories](about_pxf_dir.html)
lets use the complete topic name:  About the PXF Installation and Configuration Directories.

also, a missing period.

2021-03-22 22:25 UTC, lisakowen approved these changes

2021-03-23 00:04 UTC, dyozie approved these changes

2021-03-23 00:04 UTC, dyozie commented on docs/content/upgrade_5_to_6.html.md.erb
> +-   [Step 2: Installing PXF 6.x](#pxfinst)
Not sure why this was changed from Install to Installing?  These step titles are no longer parallel after this change.

2021-03-23 00:53 UTC, lisakowen commented on docs/content/upgrade_5_to_6.html.md.erb
> +-   [Step 2: Installing PXF 6.x](#pxfinst)
my bad.  i thought i was looking at a topic title when i made that comment.  sorry, mireia!

2021-03-23 14:08 UTC, mperezfuster commented on docs/content/upgrade_5_to_6.html.md.erb
> +-   [Step 2: Installing PXF 6.x](#pxfinst)
you were, I just went and changed this one for some reason, it's undone now!

2021-03-23 19:56 UTC, merged