Docs: Created docs content for new read Json feature
greenplum-db/pxf pull request #641
Opened 2021-05-27 17:18 UTC by mperezfuster

Created some content about the new feature for read from json.
Please let me know if other sections might need to be updated as well.
Preview: https://mireia-pxf-json.sc2-04-pcf1-apps.oc.vmware.com/pxf/6-0/using/hdfs_json.html
https://mireia-pxf-json.sc2-04-pcf1-apps.oc.vmware.com/pxf/6-0/using/objstore_json.html

2021-05-27 18:07 UTC, bradfordb-vmware reviewed
I think we might to add some an extra paragraph with the SQL statements to convert the `TEXT` column into a Postgres array column. I think @denalex has that example in the automation tests and was planning to share with you.

2021-05-27 18:07 UTC, bradfordb-vmware commented on docs/content/hdfs_json.html.md.erb
> +In some cases, you may need to retrieve all the values of an entire array within a single column. For example, when arrays are not always the same lenght, or the lenght of the array is too long to cr
```suggestion
In some cases, you may want to retrieve all the values of a JSON array within a single column. For example, when arrays are not always the same length, or the length of the array is too long to create a column for each possible array index, or when using nested arrays. For this purpose, you can define the JSON array field as a single `TEXT` column instead.
```

2021-05-27 18:07 UTC, bradfordb-vmware commented on docs/content/hdfs_json.html.md.erb
> +| Array                         | Use `[]` brackets to identify a specific array index to a member of primitive type.<br>Use `TEXT` to retrieve the full content of the array in one column.
> Use `[]` brackets to identify a specific array index

I know this was the original text, but is there any way to indicate that an integer needs to be placed inside the square brackets?

2021-05-27 18:07 UTC, bradfordb-vmware commented on docs/content/hdfs_json.html.md.erb
> +If you need to retrieve all values of the entire array within a single column, you must define the array field as `TEXT`:
```suggestion
If you need to retrieve all values of the entire array within a single column, you can define the array field as `TEXT`:
```

This is just a personal style preference, if the prevailing docs convention is to use "must" then I'd stick with that.

2021-05-27 18:07 UTC, bradfordb-vmware commented on docs/content/hdfs_json.html.md.erb
> +Note the difference between the two ways of defining the `coordinates.values[]` array: using the first example, you will obtain a column per array element, while with the second example, you will obt
```suggestion
Note the difference between the two ways of defining the `coordinates.values[]` array: using the first example, you will define a column per array element, while with the second example, you define a single column with all the values of the array.
```

2021-05-27 20:41 UTC, denalex reviewed
We also need to talk about JSON objects that we can now retrieve into TEXT columns

2021-05-27 20:41 UTC, denalex commented on docs/content/hdfs_json.html.md.erb
> +In some cases, you may need to retrieve all the values of an entire array within a single column. For example, when arrays are not always the same lenght, or the lenght of the array is too long to cr
I would think in most cases you would want the whole array. So I'd write about it first and then "in some cases" about picking a single element out of it.

2021-05-27 20:41 UTC, denalex commented on docs/content/hdfs_json.html.md.erb
> +If you need to retrieve all values of the entire array within a single column, you must define the array field as `TEXT`:
`you must define the array field as `TEXT`:` -- this is mixing the terms -- `fields` are JSON elements, `columns` are Greenplum elements. I'd say 

You can retrieve all values of the array as a single column, defined with one of the following types :`TEXT`, `VARCHAR`, or `BPCHAR`.

2021-05-28 13:25 UTC, mperezfuster commented on docs/content/hdfs_json.html.md.erb
> +| Array                         | Use `[]` brackets to identify a specific array index to a member of primitive type.<br>Use `TEXT` to retrieve the full content of the array in one column.
@lisakowen what do you think? I know there is also reference to this above the table:
"coordinates is an object composed of a text field named type and an array of integers named values. Use [] to identify specific elements of the values array as Greenplum Database external table columns"

2021-06-01 17:10 UTC, lisakowen commented on docs/content/hdfs_json.html.md.erb
> +| Array                         | Use `[]` brackets to identify a specific array index to a member of primitive type.<br>Use `TEXT` to retrieve the full content of the array in one column.
yes, i think we could use [n].

2021-06-01 17:17 UTC, dyozie requested changes

2021-06-01 17:17 UTC, dyozie commented on docs/content/hdfs_json.html.md.erb
> +In some cases, you may need to retrieve all the values of an entire array within a single column. For example, when arrays are not always the same lenght, or the lenght of the array is too long to cr
Suggest removing "entire" in this sentence.

Also, typo x2:  lenght.

2021-06-01 17:17 UTC, dyozie commented on docs/content/hdfs_json.html.md.erb
> +If you need to retrieve all values of the entire array within a single column, you must define the array field as `TEXT`:
Same suggestion to remove "entire" here.

2021-06-02 15:09 UTC, lisakowen approved these changes
looks good, a few minor comments.

2021-06-02 15:09 UTC, lisakowen commented on docs/content/hdfs_json.html.md.erb
> +Alternatively, use `[]` to identify specific elements of the `values` array as separate Greenplum Database external table columns:
<code>[<i>n</i>]</code>

2021-06-02 15:09 UTC, lisakowen commented on docs/content/hdfs_json.html.md.erb
> +If you need to identify specific elements of the `user.coordinates` array in different columns, use `[]` brackets to define the JSON array:
define ...  -> identify the JSON array element

2021-06-02 18:00 UTC, bradfordb-vmware commented on docs/content/hdfs_json.html.md.erb
> +| Array                         | Use `TEXT`, `VARCHAR` or `BPCHAR` to retrieve the contents of the array in one column.<br>Use <code>[<i>n</i>]</code> brackets to identify a specific array index to
```suggestion
| Array                         | Use `TEXT`, `VARCHAR`, or `BPCHAR` to retrieve the contents of the array in one column.<br>Use <code>[<i>n</i>]</code> brackets to identify a specific array index to a member of primitive type.<br>                                                                                           |
```

Added the missing serial comma.

2021-06-02 18:01 UTC, bradfordb-vmware commented on docs/content/hdfs_json.html.md.erb
> +In order to retrieve all the values of the `values` array within a single column, define the corresponding Greenplum Database external table column with one of the following types: `TEXT`, `VARCHAR`
```suggestion
In order to retrieve all the elements of the `values` array within a single column, define the corresponding Greenplum Database external table column with one of the following types: `TEXT`, `VARCHAR`, or `BPCHAR`.
```

2021-06-02 18:02 UTC, bradfordb-vmware approved these changes

2021-06-09 18:58 UTC, denalex approved these changes

2021-06-09 18:58 UTC, denalex commented on docs/content/hdfs_json.html.md.erb
> +
``` pre
 coordinates.values
 ```
to give an example on how the property should be referred to when reading the whole array

2021-06-09 18:58 UTC, denalex commented on docs/content/hdfs_json.html.md.erb
> +If you need to identify specific elements of the `user.coordinates` array in different columns, use `[]` brackets to identify the JSON array:
```suggestion
If you need to identify specific elements of the `coordinates.values` array in different columns, use `[]` brackets to identify the JSON array:
```

2021-06-09 18:58 UTC, denalex commented on docs/content/hdfs_json.html.md.erb
> +If you need to identify specific elements of the `user.coordinates` array in different columns, use `[]` brackets to define the JSON array:
```suggestion
If you need to identify specific elements of the `coordinates.values` array in different columns, use `[]` brackets to define the JSON array:
```

2021-06-09 18:58 UTC, denalex commented on docs/content/objstore_json.html.md.erb
> +- If you need to identify specific elements of the `user.coordinates` array in different columns, use `[]` brackets to identify the JSON array:
```suggestion
- If you need to identify specific elements of the `coordinates.values` array in different columns, use `[]` brackets to identify the JSON array:
```

2021-06-10 20:31 UTC, merged