docs - read/write avro array
greenplum-db/pxf pull request #652
Opened 2021-06-09 18:23 UTC by lisakowen

docs for https://github.com/greenplum-db/pxf/pull/636.

if i interpreted the PR correctly, pxf now supports reading/writing arrays of avro primitive types.  and also supports mapping some other types to string arrays when the avro schema is provided.

i updated the data type mapping tables.  also updated the example & DDL to use text[] for followers data field.

questions:
1.  read/write mappings - i could use some suggestions on how to present this better.  i didn't want to have a separate line for each "array of primitive type", but maybe that is needed.
2.  i assumed that pxf could support arrays of all of the primitive types (like double) even though the PR did not explicitly call that out.  let me know if this is not correct.

doc review site link:   https://docs-lisa-pxf-avroarray.sc2-04-pcf1-apps.oc.vmware.com/pxf/6-1/using/hdfs_avro.html

2021-06-09 23:41 UTC, bradfordb-vmware commented on docs/content/hdfs_avro.html.md.erb
> +| Complex type: Map, Record, or Enum  | text, with delimiters inserted between collection items, mapped key-value pairs, and record data.   |
This the table for reading from Avro files, which doesn't have those types. Avro has `date` and `timestamp` [_logical types_](http://avro.apache.org/docs/current/spec.html#Logical+Types) but we'd still be reading them from the Avro file as an `int` or `long`.

One thing that we don't mention here is that we support _both_

- array of primitive (e.g., an array of integers, none of which are null)
- array of union of null with primitive (e.g., an array of integers some of which might be null)

For both cases, we'd read them to the corresponding Greenplum array type (e.g., `int[]`).

2021-06-09 23:41 UTC, bradfordb-vmware commented on docs/content/hdfs_avro.html.md.erb
> +- When PXF generates the schema, it writes any complex type that you specify in the writable external table column definition to the Avro file as a single Avro `string` type. For example, if you writ
For the particular case of `numeric`, it will be a string because there isn't a matching Avro type for `numeric`; GPDB `numeric` is a variable storage size while the Avro numeric primitives (`int`, `long`, `float`, and `double`) are fixed (32 or 64-bit) size.

2021-06-10 00:25 UTC, denalex commented on docs/content/hdfs_avro.html.md.erb
> +| Complex type: Map, Record, or Enum  | text, with delimiters inserted between collection items, mapped key-value pairs, and record data.   |
I guess my questions is from a customer point of view -- if I have a logical type which is date or timestamp in my Avro file (and an array of those as well), and I want this info in GPDB, what should I do ? Should I map it to int ? What do I do with that int afterwards to arrive at the proper date / timestamp ? Or should I define it as `date` in GPDB and expect PXF to do the conversion ? 

Right now there is no info whatsoever for READ case and for WRITE we are saying" `date, numeric, time, timestamp, timestamptz&nbsp;and&nbsp;no Avro schema is provided | string" so we are storing them as strings that GPDB sends us, not as Avro logical types. Maybe smith to look at for the next enhancement.


.

2021-06-10 00:30 UTC, denalex commented on docs/content/hdfs_avro.html.md.erb
> +- When PXF generates the schema, it writes any complex type that you specify in the writable external table column definition to the Avro file as a single Avro `string` type. For example, if you writ
thanks for clarification @bradfordb-vmware , it reads very generically though, so "array of numerics" sounds to me like an Arya of smith with is a number, not quite a `numeric[]`. It also is not obvious that `numeric` is a `complex type`, maybe we need to explain it before giving an example.

2021-06-10 00:41 UTC, bradfordb-vmware commented on docs/content/hdfs_avro.html.md.erb
> +- When PXF generates the schema, it writes any complex type that you specify in the writable external table column definition to the Avro file as a single Avro `string` type. For example, if you writ
I agree 100% and it's unfortunate that the upstream Postgres [docs](https://www.postgresql.org/docs/9.1/datatype-numeric.html) use "numeric types" to refer to types like `smallint`, `integer`, `numeric`, ...

Perhaps we should clearly define on this page that 
- _numeric types_ refers to all types listed in Table 8-2 from the previous link
- `numeric` refers specfically to the user-specified precision GPDB type

I don't know if that helps with or adds to the confusion.

2021-06-10 09:58 UTC, mperezfuster approved these changes

2021-06-10 09:58 UTC, mperezfuster commented on docs/content/hdfs_avro.html.md.erb
> +PXF supports writing only Avro primitive types and arrays of Avro primitive types. PXF supports writing other complex types to Avro as string.
maybe "only" is not required anymore?

2021-06-10 20:27 UTC, lisakowen commented on docs/content/hdfs_avro.html.md.erb
> +| Complex type: Map, Record, or Enum  | text, with delimiters inserted between collection items, mapped key-value pairs, and record data.   |
i added a link to the avro spec for primitive/complex/logical types.  i separately address the logical types (as a group) in the "data type" intro.  also added a table row for these for read.

re-pushed the review site, may need to refresh.

2021-06-10 20:27 UTC, lisakowen commented on docs/content/hdfs_avro.html.md.erb
> +- When PXF generates the schema, it writes any complex type that you specify in the writable external table column definition to the Avro file as a single Avro `string` type. For example, if you writ
for this specific issue, i clarify that we are referring to the greenplum `numeric` type.

2021-06-11 18:12 UTC, bradfordb-vmware commented on docs/content/hdfs_avro.html.md.erb
> +| Logical type: decimal, date, time, timestamp, duration | text |
This one is not quite correct. When PXF writes GPDB date/time types to Avro, it saves the data in the Avro file with type `string`. To read this back in to GPDB, you would want to have your column be of type `text` as you have here.

However, Avro natively stores

- the `date` logical type as an `int`
- the `time-millis`, `timestamp-millis`, `local-timestampe-millis` (millisecond precision) as an `int`
- the `time-micros`, `timestamp-micros`, `local-timestamp-micros (microsecond precision) as a `long`
- the `duration` logical type is stored as a `fixed` with size 12

To read these fields, the user will need to declare their GPDB columns as `int`, `bigint`, or `bytea` (respectively).

2021-06-11 20:43 UTC, dyozie requested changes

2021-06-11 20:43 UTC, dyozie commented on docs/content/hdfs_avro.html.md.erb
> +Avro supports logical data types including include decimal, date, time, and duration types. You must similarly map these data types to the Greenplum Database `text` type.
including include -> including

2021-06-12 00:42 UTC, ashuka24 commented on docs/content/hdfs_avro.html.md.erb
> +| bigint[], boolean[], bytea[], double[], int[], real[], text[] <br>(*no Avro schema is provided*) | long[], boolean[], bytes[], double[], int[], float[], string[] |
Do we need to specify here that if no avro schema is provided, it only creates a one-dimensional array?

2021-06-13 17:27 UTC, lisakowen commented on docs/content/hdfs_avro.html.md.erb
> +| Logical type: decimal, date, time, timestamp, duration | text |
are you saying that if the avro file was generated by another source, pxf could read date/timemilli/timemicro/duration as int/int/bigint/bytea.  would decimal be read as text?

in the case where pxf generated the avro file, and those types were written, the type is string already, right?  so it would be a string->text mapping.

2021-06-13 17:28 UTC, lisakowen commented on docs/content/hdfs_avro.html.md.erb
> +| bigint[], boolean[], bytea[], double[], int[], real[], text[] <br>(*no Avro schema is provided*) | long[], boolean[], bytes[], double[], int[], float[], string[] |
i was thinking that `[]` would imply a one-dimensional array.  i can also explicitly state that.

2021-06-14 18:25 UTC, bradfordb-vmware commented on docs/content/hdfs_avro.html.md.erb
> +| Logical type: decimal, date, time, timestamp, duration | text |
If the Avro file was generated by another source, then PXF **would have to** read `date`/`timemilli`/`timemicro`/`duration` as an `int`/`int`/`long`/`bytea`. If you try to read as `text`, it would fail with the following error:

```console
ERROR:  For field value schema requires type TEXT but input record has type INTEGER  (seg0 slice1 127.0.1.1:6000 pid=519527)
```

If PXF wrote the Avro file, then the GPDB column types for date/timestamp/etc would be written as `string` and it would be a `string` to `text` mapping.

2021-06-16 23:17 UTC, lisakowen commented on docs/content/hdfs_avro.html.md.erb
> +| Logical type: decimal, date, time, timestamp, duration | text |
thanks, @bradfordb-vmware .  i created separate rows for the (groups of) logical types.

how do we handle the Avro decimal type on read?  do we need to call that type out?

2021-06-22 17:15 UTC, bradfordb-vmware commented on docs/content/hdfs_avro.html.md.erb
> +| Complex type: Array (any dimension) of type: boolean, bytes, double, float, int, long, string | array (any dimension) of type: boolean, bytea, double, real, bigint, text   |
I don't think we can put `NOT NULL` on columns in external tables, so I think we can combine this row and the following one.

2021-06-22 17:16 UTC, bradfordb-vmware approved these changes

2021-06-22 18:14 UTC, merged