docs - new default fetchSize when reading from MySQL
greenplum-db/pxf pull request #729
Opened 2021-12-15 19:16 UTC by lisakowen

docs for https://github.com/greenplum-db/pxf/pull/721.

new default value for jdbc.statement.fetchSize when accessing a mysql database.

2021-12-15 19:30 UTC, bradfordb-vmware requested changes

2021-12-15 19:30 UTC, bradfordb-vmware commented on docs/content/jdbc_cfg.html.md.erb
> +| jdbc.statement.fetchSize | The number of rows to fetch/buffer when reading from the external database table. | The number of rows. The default read fetch size for MySQL is `-2147483648` (`Integer.M
I think we need to explain this special value for MySQL. According to the MySQL docs (https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-implementation-notes.html), setting this value enables streaming the results back one row at a time.

2021-12-16 19:56 UTC, denalex approved these changes

2021-12-16 20:33 UTC, ashuka24 approved these changes

2021-12-17 17:07 UTC, lisakowen commented on docs/content/jdbc_cfg.html.md.erb
> +| jdbc.statement.fetchSize | The number of rows to fetch/buffer when reading from the external database table. | The number of rows. The default read fetch size for MySQL is `-2147483648` (`Integer.M
i will address this later.

2021-12-17 17:07 UTC, merged