Fix: For reading the records correctly from a MultiLine JSON file
greenplum-db/pxf pull request #738
Opened 2022-01-19 02:20 UTC by hpandeycodeit

There is an issue currently where in large Multiline JSON files (>128MB) with special characters, the bytes are not counted correctly. This could result in duplicate records in the GPDB.
    
This PR fixes the above issue.

2022-01-19 04:35 UTC, denalex commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/JsonRecordReader.java
> +        parser = new PartitionedJsonParser(fileIn);
what about the codec case from above, the codec was used to create the InputStream and the value is saved in `is` variable, but it seems not to be used anymore ?

2022-01-19 04:35 UTC, denalex commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +		while ((i = fileIn.read()) != EOF) {
this method now returns a byte, not a character, since we switched from `InputStreamReader` to a subclass of `InputStream`. Not sure if the rest of the logic will be ok with that. `(char)` cast will only work for ASCII. Also, reading bytes and representing them as `int` is not very efficient.

2022-01-19 04:35 UTC, denalex commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
> +    private static String jsonFile = "src/test/resources/parser-tests/offset/input.json";
I think there is a way to refer to test resources without `src/test/resources/` path, smth like:
```
File f = new File(this.getClass().getClassLoader().getResource("example.txt").toURI());
```

2022-01-19 04:35 UTC, denalex commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserSeekTest.java
> +    }
not sure what this test is doing, why we seek to 0 each time and how is it different from NoSeek test.

2022-01-19 04:35 UTC, denalex commented on server/pxf-json/src/test/resources/parser-tests/offset/input.json
> +
We need tests that work with UTF-8 multibyte chars to verify the issue. Also tests that introduce split sizes that fall in the middle of the current test file to make sure the logic works across splits for the same file (as well as across file boundaries, which maybe current Seek test is doing ?)

2022-01-19 20:14 UTC, bradfordb-vmware commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> -		this.inputStreamReader = new InputStreamReader(is, StandardCharsets.UTF_8);
This breaks the use-case where `identifier` (i.e., `jsonMemberName` in `JsonRecordReader`) contains non-ASCII characters. Consider JSON data that looks like:

```json
[
  {
    "cüsötmerstätüs": "...",
    ...
  },
  {
    "cüsötmerstätüs": "...",
    ...
  },
  ...
]
```

with an external table 

```sql
CREATE EXTERNAL TABLE pxf_multiline_json (<columns>)
LOCATION ('pxf://data.json?profile=hdfs:json&identifier=cüsötmerstätüs') ON ALL
FORMAT 'CUSTOM' ( FORMATTER='pxfwritable_import' )
ENCODING 'UTF8';
```

Running `SELECT count(*) FROM pxf_multiline_json` will return a count of zero while the master branch returns a non-zero count.

Since JSON identifiers can contain UTF-8 characters, I think we need to keep the `InputStreamReader`.

2022-01-19 21:45 UTC, ashuka24 commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +	public PartitionedJsonParser(FSDataInputStream fileIn  ) {
nitpick: 
```suggestion
	public PartitionedJsonParser(FSDataInputStream fileIn) {
```

2022-01-19 21:45 UTC, ashuka24 commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> + 		this.fileIn =   fileIn;
nitpick: 
```suggestion
 		this.fileIn = fileIn;
```

2022-01-19 21:45 UTC, ashuka24 commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
> +        assertEquals(38, fileIn.getPos());
seems a little strange to me that we are not checking bytes read by calling the underlying datatype's `getPos()` function instead of just calling `parser.getBytesRead`. can we keep `getBytesRead` as wrapper over this function?

2022-02-01 18:34 UTC, bradfordb-vmware requested changes

2022-02-01 18:34 UTC, bradfordb-vmware commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +    private static final char BACKSLASH = '\\';
It looks like this file was re-indenting using spaces instead of tabs which makes it hard to view what functionally was changed. Can we leave this file indented with tabs so that the PR highlights the code changes?

2022-02-01 18:34 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserNoSeekTest.java
> +import java.io.*;
We want to avoid wildcard imports. You might need to configure your IDE to not use them; I don't think IntelliJ allows you to disable them completely but you can configure it to have really high number.

2022-02-02 21:35 UTC, hpandeycodeit commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +    private static final char BACKSLASH = '\\';
There was some issue with the line endings which is fixed so you should see only the changes related to this PR.

2022-02-02 21:35 UTC, hpandeycodeit commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserNoSeekTest.java
> +import java.io.*;
fixed this as well.

2022-02-02 22:35 UTC, ashuka24 commented on server/pxf-json/src/test/resources/parser-tests/offset/input.json
> +
nit pick: remove extra lines

2022-02-02 22:35 UTC, ashuka24 commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
> +
nitpick: remove extra line

2022-02-02 22:35 UTC, ashuka24 commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +				//in case of START_BRACE "{" , subtract one byte as we will be counting this
why do we not have to worry about the ending brace?

2022-02-02 22:40 UTC, bradfordb-vmware commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +			bytesRead += Character.toString(c).getBytes(StandardCharsets.UTF_8).length;
I wonder if it might be more performant to maintain a `CharBuffer` that we append characters to and then at the end of the function, call `charBuffer.toString.getBytes(StandardCharsets.UTF_8).length`.

2022-02-02 22:40 UTC, bradfordb-vmware commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +						bytesRead += currentObject.toString().getBytes(StandardCharsets.UTF_8).length;
We're calling `currentObject.toString()` twice here; I'd extract to a local variable.

```java
final String result = currentObject.toString()
bytes += result.getBytes(StandardCharsets.UTF_8).length;
return result
```

2022-02-02 22:40 UTC, bradfordb-vmware commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> -			bytesRead++;
I think we are still (potentially) under counting. There are some places where we call `currentObject.setLength(0)` and/or `currentObject.delete(...)` where we are not including those characters' bytes in `bytesRead`.

I wonder if it might be simpler to add an additional `CharBuffer` that we append every character read (`c`)  to. When the function exits, we can call `charBuffer.toString.getBytes(StandardCharsets.UTF_8).length`

As an example of where I think we might be miss counting is the following JSON where `memberName` is `id`:

```json
[
  {
    "id": ...,
  },
  {
    "skip": ...,
  },
  {
    "id": ...,
  }
]
```

Here the second object does not contain the `memberName` we are looking for, so we read past it to the third object but we only account for the third object's bytes.

2022-02-02 22:40 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
> +    @BeforeEach
Style-nit: Can we move the setup method to the beginning of the class?

2022-02-02 22:40 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
> +    public LongWritable createKey() {
Does this need to be public?

2022-02-02 22:40 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
> +    public Text createValue() {
Does this need to be public?

2022-02-02 22:40 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
> +        fileSplit = new FileSplit(path, start, 100l, hosts);
For long literals, we should use `L` because it is really hard to tell (depending on the font) if that is a lowercase L (`l`) or a one (`1`).

2022-02-02 22:40 UTC, bradfordb-vmware commented on server/pxf-json/src/test/resources/parser-tests/offset/input.json
> +
This test set includes two-byte UTF-8 code points (umlauts) but we should include wider code points (three and four bytes are valid). As an example 'hello' in Chinese is `你好` which is two code points and is encoded using 6 total bytes. An example code point that is encoded with four bytes is `🦈` (shark emoji).

2022-02-03 00:04 UTC, denalex commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
>  public class PartitionedJsonParserOffsetTest {
```suggestion
public class PartitionedJsonParserTest {
```

2022-02-03 00:04 UTC, denalex commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
> +        assertEquals(184, jsonRecordReader.getPos() - start);
this is testing `jsonRecordReader` in the unit test for the `PartitionedJsonParser`. Maybe create a separate utnit test class for testing the reader specifically. Parser test needs to assert the results of parsing

2022-02-03 00:04 UTC, denalex commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
> +    }
maybe we should have a set of tests using codec to exercise that flow.

2022-02-07 21:49 UTC, hpandeycodeit commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> -			bytesRead++;
I tried with CharBuffer but it needs converting every character to a UTF. I have used StringBuilder Object Instead.

2022-02-07 21:50 UTC, hpandeycodeit commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +				bytesRead--;
Changed the logic so don't have to check for `{`

2022-02-07 21:50 UTC, hpandeycodeit commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +				//in case of START_BRACE "{" , subtract one byte as we will be counting this
Changed the logic so don't have to check for `{`

2022-02-07 21:51 UTC, hpandeycodeit commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
> +        assertEquals(184, jsonRecordReader.getPos() - start);
Created a separate test class for `jsonRecordReader`

2022-02-07 21:51 UTC, hpandeycodeit commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserOffsetTest.java
> +    }
Added the test for codec as well.

2022-02-07 21:52 UTC, hpandeycodeit commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +			bytesRead += Character.toString(c).getBytes(StandardCharsets.UTF_8).length;
I need some clarification on this. How this will help with optimization? In both the cases it will go through the same logic.

2022-02-15 19:29 UTC, bradfordb-vmware approved these changes

2022-02-15 19:29 UTC, bradfordb-vmware commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +	private StringBuilder charObject;
I think the name `charObject` is a little too generic -- maybe something like `uncountedCharsReadFromStream`? I don't know if that's the best name either but it should reflect that purpose of this builder -- buffering characters read from the stream that haven't been added to `bytesRead`.

2022-02-15 19:29 UTC, bradfordb-vmware commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +			charObject.append(c);
Minor nit: can we move this up to right after the cast to `char` so that it matches the loop in `scanToFirstBeginObject`?

2022-02-16 20:19 UTC, denalex commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +			uncountedCharsReadFromStream.append(c);
if we are reading a large file and the object we need is way at the end (or not even present) the `StringBuffer` will grow too large. Should we keep a long counter of characters read and update `bytesRead` and reset the `StringBuffer` every N characters (say 8096) ?

2022-02-16 20:23 UTC, denalex commented on server/pxf-json/src/test/resources/parser-tests/offset/input.json
> +{"cüsötmerstätüs":"välid","name": "äää", "year": "2022", "address": "söme city", "zip": "95051"},
```suggestion
{"cüstömerstätüs":"välid","name": "äää", "year": "2022", "address": "söme city", "zip": "95051"},
```
unless intentional. Here and everywhere else, seems like a typo

2022-02-16 20:29 UTC, denalex commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserTest.java
> +        assertEquals(11, parser.getBytesRead() - result.length());
numbers here are try to visualize / verify. Maybe put a comment what we expect to see in the input file at these byte offsets. Also, the math subtracts number of characters `result.length()` from number of bytes read `parser.getBytesRead()`. I don't think this is correct, I think you need to do `result.getBytes(UTF_8).length` for proper accounting. If I am right, then how is that the test does not fail ?

2022-02-16 20:39 UTC, denalex commented on server/pxf-json/src/test/resources/parser-tests/offset/input.json
> +]
I think we should try to test more files with different content, some I can think of:
* empty files
* empty collection files (contains only `[]` or `{}`)
* files that have no elements matching the keyword
* files that have some records matching the keyword intermixed with the ones that don't
* records where the keyword is not at the top level, asserting that it did not match

2022-02-16 20:46 UTC, denalex commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParserTest.java
> +       File file = new File(this.getClass().getClassLoader().getResource("parser-tests/offset/input.json").toURI());
nit: alignment

2022-02-16 20:56 UTC, denalex commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        assertEquals(184, jsonRecordReader.getPos() - start);
it would be nice to assert that the record it read is expected (i.e. look inside the record or just compare JSON strings)

2022-02-16 20:58 UTC, denalex commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        }
we need to assert more, this should be similar to `testWithCodec`

2022-02-17 19:18 UTC, hpandeycodeit commented on server/pxf-json/src/test/resources/parser-tests/offset/input.json
> +]
Added these additional tests and fixed other comments as well.

2022-02-18 00:38 UTC, denalex commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/JsonRecordReader.java
> +        fileIn = fs.open(split.getPath());
it does not seem we still need to have `fileIn` to be a class member. I think having it as local variable, as before, is sufficient as we are not accessing it from any other method.

2022-02-18 00:38 UTC, denalex commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +		this.uncountedCharsReadFromStream = new StringBuilder(8192);
let's extract `8192` as a constant

2022-02-18 00:38 UTC, denalex commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +	private StringBuilder uncountedCharsReadFromStream;
```suggestion
	private final StringBuilder uncountedCharsReadFromStream;
```

2022-02-18 00:38 UTC, denalex commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +		int i = inputStreamReader.read();
this read character can be EOF here, which is not even a character by itself, it is value -1 that signifies "nothing more to read", so we need to check for this and not append / count it.

2022-02-18 00:38 UTC, denalex commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +		if (uncountedCharsReadFromStream.length() > 8096) {
I think you meant `8192`, so let's use the constant here. And that's too late, this will cause StringBuilder to expand capacity, we need to prevent it going over the target capacity.

2022-02-24 00:24 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        assertEquals("", data.toString());
```suggestion
        assertFalse(jsonRecordReader.next(key, value));
        assertEquals(12, jsonRecordReader.getPos());
```

Since `jsonRecordReader.next(key, value)` is only supposed to return `true` if a key/value was read, I don't know if we need to assert anything about `data`.

2022-02-24 00:24 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        if (jsonRecordReader.next(key, data)) {
Same comment as the previous two tests.

2022-02-24 00:24 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        assertEquals(4, recordCount);
Do we expect that all of the bytes of `mixed_input.json` will have been read at this point? Can we assert the value of `jsonRecordReader.getPos()`?

2022-02-24 00:24 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        assertEquals(1, recordCount);
Do we expect that all of the bytes of `mixed_input.json` will have been read at this point? Can we assert the value of `jsonRecordReader.getPos()`?

2022-02-24 00:24 UTC, bradfordb-vmware commented on server/pxf-json/src/test/resources/parser-tests/offset/complex_input.json
> +[{
I don't think this file is valid JSON -- when I try to parse it with `jq`, I get an error:

```console
$ <complex_input.json jq
parse error: Objects must consist of key:value pairs at line 16, column 1
```

2022-02-24 00:24 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        // Split After { before MEMBER_NAME or After RECORD_MEMBER_IDENTIFIER will cause the record to skip
I had to read and re-read this description to understand the test and I am still not sure that I do:

I think we are testing the case where a file split starts after the JSON `BEGIN_OBJECT` (i.e., `{`) but before the identifier we are looking for (e.g., `{<split-start>"<identifier>"...`). In this case, we expect the record reader to skip over this object entirely.

Is that a correct understanding of this test?

2022-02-24 00:24 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        assertEquals(1, recordCount);
Here I think it would be really helpful to assert on what we expect data to be. Since `data` is expected to be a valid JSON object, it might even make sense to convert it to an object and assert the field values:

```java
JsonNode jsonNode = objectMapper.readTree(data);
String color = jsonNode.get("color").asText();
assertEquals("red", color);
...
```

2022-02-24 00:24 UTC, bradfordb-vmware commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        file = new File(this.getClass().getClassLoader().getResource("parser-tests/seek/seek-into-mid-object-1/input.json").toURI());
I know this PR doesn't add this JSON file, but it is not valid JSON

```console
$ <seek/seek-into-mid-object-1/input.json jq
parse error: Invalid numeric literal at line 3, column 11
```

2022-02-24 17:32 UTC, hpandeycodeit commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        // Split After { before MEMBER_NAME or After RECORD_MEMBER_IDENTIFIER will cause the record to skip
Yes that is correct.

2022-02-24 19:37 UTC, hpandeycodeit commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        file = new File(this.getClass().getClassLoader().getResource("parser-tests/seek/seek-into-mid-object-1/input.json").toURI());
This is due to the `<SEEK>` in these files where the other tests are reading this keyword as an offset.

2022-02-24 19:38 UTC, hpandeycodeit commented on server/pxf-json/src/test/resources/parser-tests/offset/complex_input.json
> +[{
Fixed this.

2022-02-24 19:39 UTC, hpandeycodeit commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        assertEquals(1, recordCount);
Added assertions on some of these data values and fixed other comments as well.

2022-02-25 00:58 UTC, ashuka24 commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +	private static final long CHARS_READ_LIMIT = 8192L;
Where did this number come from? Is it a standard char limit value?

2022-02-25 00:58 UTC, ashuka24 commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +
nit: unnecessary new line

2022-02-25 00:58 UTC, ashuka24 commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        jsonRecordReader.next(key, data); // why it's reading beyond split boundaries?? Have more clarification around the boundary
Does this comment need to be addressed?

2022-02-25 00:58 UTC, ashuka24 commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +     * The Split size is large only single spilt will be able to read all the records.
```suggestion
     * The Split size is large so a single split will be able to read all the records.

2022-02-25 19:41 UTC, hpandeycodeit commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +	private static final long CHARS_READ_LIMIT = 8192L;
Not standard. It is `8K ( 1024*8)` chars count limit that we thought would be good to reset the buffer in case of very large object or zipped file to avoid buffer overflow.

2022-02-25 19:42 UTC, hpandeycodeit commented on server/pxf-json/src/test/java/org/greenplum/pxf/plugins/json/parser/JsonRecordReaderTest.java
> +        jsonRecordReader.next(key, data); // why it's reading beyond split boundaries?? Have more clarification around the boundary
This was already addressed in the comments already. Missed to remove it. Thanks! 

Fixed rest of the comments as well.

2022-03-01 05:55 UTC, denalex approved these changes

2022-03-01 05:55 UTC, denalex commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +		this.uncountedCharsReadFromStream = new StringBuilder();
```suggestion
		this.uncountedCharsReadFromStream = new StringBuilder(CHARS_READ_LIMIT);
```

2022-03-01 05:55 UTC, denalex commented on server/pxf-json/src/main/java/org/greenplum/pxf/plugins/json/parser/PartitionedJsonParser.java
> +		if (i != -1) {
```suggestion
		if (i != EOF) {
```

2022-03-02 00:53 UTC, merged