Remove unused TARGET_OS and TARGET_OS_VERSION references
greenplum-db/pxf pull request #748
Opened 2022-02-04 00:40 UTC by ashuka24

From the concourse scripts and pipelines

Also remove Centos6 check for PXF 6+

Co-authored-by: Ashuka Xue <axue@vmware.com>
Co-authored-by: Bradford Boyle <bradfordb@vmware.com>

2022-02-04 18:00 UTC, bradfordb-vmware approved these changes

2022-02-04 20:40 UTC, denalex requested changes
Whatever is here looks good, but my search in IDE reveals more files with TARGET_OS_VERSION variable used:
- add_osl_rpm.bash
- add_osl_deb.bash
- generate_tarball_from_rpm.bash

Please do a global search to make sure all files are accounted and modified.

2022-02-04 23:12 UTC, denalex commented on concourse/pipelines/templates/build_pipeline-tpl.yml
> +      REDHAT_DISTRIBUTION: 7
are we gonna have a similar job for RHEL8 ?

2022-02-04 23:12 UTC, denalex commented on concourse/pipelines/templates/build_pipeline-tpl.yml
> +      REDHAT_DISTRIBUTION: 7
are we gonna have a similar job for RHEL8 ?

2022-02-04 23:12 UTC, denalex commented on concourse/scripts/add_osl_rpm.bash
> +rpm_file_name=$(find pxf_artifacts -type f -name "pxf-gp${GP_VER}-*-1.el${REDHAT_DISTRIBUTION}.x86_64.rpm" -printf "%f\n")
will RHEL8 RPM still have extension `.el8` or will it be full `rhel8` in which case this might not work for rhel8  ?

2022-02-04 23:12 UTC, denalex commented on concourse/scripts/generate_tarball_from_rpm.bash
> +target_os_ver="$(rpm -qp --queryformat '%{release}' greenplum-db-5.29.2-rhel7-x86_64.rpm)"
why does this hardcode the rpm name ?

2022-02-04 23:12 UTC, denalex commented on concourse/tasks/add_osl_rpm.yml
> +  REDHAT_DISTRIBUTION:
we really mean version here, why not call it `REDHAT_VERSION` or `REDHAT_MAJOR_VERSION` ?

2022-02-04 23:42 UTC, ashuka24 commented on concourse/pipelines/templates/build_pipeline-tpl.yml
> +      REDHAT_DISTRIBUTION: 7
correct, we will have a similar OSL job for RHEL8

2022-02-04 23:42 UTC, ashuka24 commented on concourse/pipelines/templates/build_pipeline-tpl.yml
> +      REDHAT_DISTRIBUTION: 7
we will not have a similar job for generating a tarball from rpm as Releng only consumes rpms for PXF 6+

2022-02-04 23:50 UTC, bradfordb-vmware commented on concourse/scripts/generate_tarball_from_rpm.bash
> +target_os_ver="$(rpm -qp --queryformat '%{release}' greenplum-db-5.29.2-rhel7-x86_64.rpm)"
I think this was mistakenly included. We'll need to remove it.

2022-02-04 23:53 UTC, bradfordb-vmware commented on concourse/tasks/add_osl_rpm.yml
> +  REDHAT_DISTRIBUTION:
In the RPM spec file, the macro we use is `%{dist}`(https://docs.fedoraproject.org/en-US/packaging-guidelines/DistTag/) which is a distribution tag. We picked `REDHAT_DISTRIBUTION` to match with that.

2022-02-05 00:01 UTC, denalex commented on concourse/tasks/add_osl_rpm.yml
> +  REDHAT_DISTRIBUTION:
strictly speaking DistTag will produce `el7` string, here we are only expecting 7. I still believe _MAJOR_VERSION is a better suffix, but I'm ok with whatever

2022-02-05 00:27 UTC, ashuka24 commented on concourse/scripts/add_osl_rpm.bash
> +rpm_file_name=$(find pxf_artifacts -type f -name "pxf-gp${GP_VER}-*-1.el${REDHAT_DISTRIBUTION}.x86_64.rpm" -printf "%f\n")
RHEL8 RPMs should still be `.el8`

2022-02-07 22:56 UTC, denalex approved these changes

2022-02-07 23:18 UTC, merged