Replace shell parameter expansions with Make functions
greenplum-db/pxf pull request #901
Opened 2022-11-22 02:15 UTC by bradfordb-vmware

The various Makefiles used to build PXF contain a number of shell parameter expansions that either work or cause Make to fail with a syntax error, depending on the version of bash and Make that are installed. This commit replaces these parameter expansions witl Make text functions that are more portable.

Authored-by: Bradford D. Boyle <bradfordb@vmware.com>

2022-11-22 08:03 UTC, edespino requested changes

2022-11-22 08:03 UTC, edespino commented on cli/go/src/pxf-cli/Makefile
> +TARGET := $(notdir ${PWD})
I believe the lack of using the `shell` command causes an interesting side-effect. With the PR version, if the Makefile is referenced using the make `-C` option, the TARGET value will vary dependent on the directory in which the make command is invoked.

Below, I have provided three examples to consider. The first is the original version. the second is the PR version, and the third is an alternate version. The output below demonstrates 

```
======================================================================
Original version:

Notice how the value for TARGET is IDENTICAL in the following cases

- The make command is invoked from the same directory as the Makefile
- The make command is invoked from another directory while referencing
  the directory of the Makefile via a make -C option.
----------------------------------------------------------------------
TARGET := $(shell echo $${PWD\#\#*/})
======================================================================

(base) eespino:workspace/ $ pwd
/Users/eespino/workspace
(base) eespino:workspace/ $ cat Makefile
TARGET := $(shell echo $${PWD\#\#*/})

target_is:
        echo ${TARGET}
(base) eespino:workspace/ $ make target_is
echo workspace
workspace
(base) eespino:workspace/ $ cd ..
(base) eespino:~/ $ pwd
/Users/eespino
(base) eespino:~/ $ make -C workspace target_is
echo workspace
workspace
(base) eespino:~/ $





======================================================================
PR version:

Notice how the value for TARGET is DIFFERENT in the following cases

- The make command is invoked from the same directory as the Makefile
- The make command is invoked from another directory while referencing
  the directory of the Makefile via a make -C option.
----------------------------------------------------------------------
TARGET := $(notdir ${PWD})
======================================================================

(base) eespino:workspace/ $ pwd
/Users/eespino/workspace
(base) eespino:workspace/ $ cat Makefile
TARGET := $(notdir ${PWD})

target_is:
        echo ${TARGET}
(base) eespino:workspace/ $ make target_is
echo workspace
workspace
(base) eespino:workspace/ $ cd ..
(base) eespino:~/ $ pwd
/Users/eespino
(base) eespino:~/ $ make -C workspace target_is
echo eespino
eespino





======================================================================
Alternate version (to consider):

Notice how the value for TARGET is IDENTICAL in the following cases

- The make command is invoked from the same directory as the Makefile
- The make command is invoked from another directory while referencing
  the directory of the Makefile via a make -C option.
----------------------------------------------------------------------
TARGET := $(notdir $(shell pwd))
======================================================================

(base) eespino:workspace/ $ pwd
/Users/eespino/workspace
(base) eespino:workspace/ $ cat Makefile
TARGET := $(notdir $(shell pwd))

target_is:
        echo ${TARGET}
(base) eespino:workspace/ $ make target_is
echo workspace
workspace
(base) eespino:workspace/ $ cd ..
(base) eespino:~/ $ pwd
/Users/eespino
(base) eespino:~/ $ make -C workspace target_is
echo workspace
workspace
```

2022-11-22 18:06 UTC, bradfordb-vmware commented on cli/go/src/pxf-cli/Makefile
> +TARGET := $(notdir ${PWD})
Good catch with `${PWD}` not updating when invoking as `make -C <path>`. It looks like Make as a variable `$(CURDIR)` that it will update so I've updated the PR to use this.

2022-11-23 07:00 UTC, edespino approved these changes
+1 - with CURDIR use.

2022-11-23 07:00 UTC, edespino commented on cli/go/src/pxf-cli/Makefile
> +TARGET := $(notdir $(CURDIR))
Nice! I have verified CURDIR is working as expected. Thank you.
```
GNU Make 4.3
GNU Make 4.1
GNU Make 3.81
```

2022-11-23 17:51 UTC, denalex approved these changes

2022-11-28 16:33 UTC, merged