Add logging to the LineBreakAccessor for the write
greenplum-db/pxf pull request #979
Opened 2023-06-09 19:54 UTC by hpandeycodeit

Add Log.trace logging to the LineBreakAccessor for the write. 
This will help in investigation in case we need to investigate any issues.

2023-06-09 20:21 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +            }
great, but let's re-arrange a bit, get rid of new variable `byteCount`, adjust logged message, do calculations only if `LOG.trace` is enabled and choose a window that will log about every 5 secs. We have seen the upload speed of 8MB/sec, so like 1000 buffers per sec or 5000 buffers per 5 secs. Otherwise the log will be littered with entries. Or we can introduce a property that can manage the frequency.
```suggestion
            InputStream inputStream = (InputStream) onerow.getData();
            final byte[] buffer = new byte[bufferSize];
            final int frequency = 5000 * bufferSize;

            // the logic below is copied from IOUtils.copyLarge to add logging
            long count = 0;            
            int n;
            while (-1 != (n = inputStream.read(buffer))) {
                dos.write(buffer, 0, n);
                count += n;
                if (LOG.isTraceEnabled() && n % frequency == 0) {
                    // log this message after every frequency*8K (default) bytes
                    LOG.trace("wrote {} additional bytes, total so far {} (buffer size {})", n, count, bufferSize);
                }
            }
```

2023-06-09 22:34 UTC, ashuka24 commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +            final int frequency = 5000 * bufferSize;
can we add a comment about why we use the value 5000 so that we do not have a floating magic number around? 

is this a value that we would want to be able to toggle somehow?

2023-06-09 23:25 UTC, yimingli-vmware approved these changes

2023-06-10 23:36 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +            }
Also, since we will be printing not for every row, maybe using DEBUG level here will be more appropriate

2023-06-12 21:48 UTC, ashuka24 commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +            final int frequency = 5000 * bufferSize;
Sure? we use 5 seconds because we have seen an upload speed of 8 MB/sec. What happens if the upload speed is significantly better or significantly worse, would we want to modify the frequency at which we are logging?

2023-06-20 19:50 UTC, bradfordb-vmware requested changes

2023-06-20 19:50 UTC, bradfordb-vmware commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +                if (LOG.isDebugEnabled() && n % frequency == 0) {
I think this logic is wrong:
Since `n` is the number of bytes read into the buffer, it should always be less than or equal to `bufferSize` and `frequency` is a multiple of `bufferSize` so `n` will always be less than `frequency`. The only value of `n` for which `n % frequency == 0` is `n = 0`.

I _think_ you want to check `count % frequency == 0`.

2023-06-26 20:00 UTC, denalex requested changes

2023-06-26 20:00 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +            final int logIntervalBytes = 32 * 1024 * 1024;
this should be a class-level constant

2023-06-26 20:00 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +                if (LOG.isDebugEnabled() && count % logIntervalBytes == 0) {
`count % logIntervalBytes == 0` still assumes we read the full buffer at a time, need more robust logic here then

also the message below `wrote {} additional bytes` with parameter value `n` is incorrect since the loop will execute many times, so `the number of additional bytes` will be way larger than `n`.

2023-07-06 17:19 UTC, denalex requested changes

2023-07-06 17:19 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +                    LOG.debug("wrote {} bytes, total so far {} (buffer size {})", n, count, bufferSize);
this is not correct, `wrote {} bytes` with parameter n -- the logic will write more than `n` bytes between the iterations.

2023-07-06 21:52 UTC, hpandeycodeit commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +                    LOG.debug("wrote {} bytes, total so far {} (buffer size {})", n, count, bufferSize);
Introduced another variable that will calculate the bytes in between iterations and update here in the error message.

2023-07-06 23:27 UTC, denalex reviewed
let's rename `totalBytesCount` into `iterationByteCount` to avoid confusion and make these local vars

2023-07-06 23:27 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +    private long totalBytesCount;
neither of these have to be class fields, just local vars

2023-07-06 23:27 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +                    LOG.debug("wrote {} bytes, total so far {} (buffer size {})", totalBytesCount, count, bufferSize);
```suggestion
                    LOG.debug("wrote {} bytes, total so far {} (buffer size {})", iterationByteCount, count, bufferSize);
```

2023-07-06 23:27 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +                    totalBytesCount = 0;
```suggestion
                    iterationByteCount = 0;
```

2023-07-06 23:27 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +                totalBytesCount +=n;
```suggestion
```

2023-07-06 23:27 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +                count += n;
```suggestion
                count += n;
                iterationByteCount += n;
```

2023-07-07 16:45 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +                iterationCount++;
if debug is not enabled, `iterationCount` will never be zeroed and can go above 2B for large dataset, let's make it a `long`. Also, maybe change `&& iterationCount == 100` to `&& (iterationCount % 100 == 0)` and remove zeroing out the iteration count for uniformity.

2023-07-07 21:54 UTC, ashuka24 commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +            long count = 0;
It looks like `count` is just the total accumulated number of bytes for the input stream. Could we update the name of the variable to reflect that?

2023-07-10 17:39 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +            LOG.debug("Wrote {} bytes to outputStream using a buffer of size {}", iterationCount, bufferSize);
```suggestion
            LOG.debug("Wrote {} bytes to outputStream using a buffer of size {}", totalByteCount, bufferSize);
```

2023-07-10 17:41 UTC, denalex commented on server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/LineBreakAccessor.java
> +            return iterationCount > 0;
while this is correct, should we keep it in the spirit of the original code that checked the number of bytes written (vs number of iterations ?)
```suggestion
            return totalByteCount > 0;
```

2023-07-10 19:05 UTC, denalex approved these changes

2023-07-10 20:40 UTC, ashuka24 approved these changes

2023-07-10 21:01 UTC, merged