Inclusive Terminology changes
greenplum-db/pxf pull request #995
Opened 2023-07-10 18:32 UTC by hpandeycodeit

Following terms are changed/renamed: 

Master -> Coordinator
Slave -> Secondary 
whitelist -> allowlist

2023-07-10 19:02 UTC, denalex reviewed
I would expect the majority of changes in `pxf-cli` and its tests. Will that be a separate PR ?

2023-07-10 23:33 UTC, hpandeycodeit commented on automation/src/main/java/org/greenplum/pxf/automation/components/common/ShellSystemObject.java
> +            "COORDINATOR_DATA_DIRECTORY",
No, It won't work. It reads this from `default.xml`  for MASTER_DATA_DIRECTORY and fails with Null pointer. Reverted it.

2023-07-10 23:35 UTC, hpandeycodeit commented
> I would expect the majority of changes in `pxf-cli` and its tests. Will that be a separate PR ?

@denalex I haven't done changes in pxf-cli since there is no Coordinator host in GP5/GP6. Not sure if we can make differentiate it at version level on the CLI?

2023-07-12 17:54 UTC, ashuka24 commented on automation/src/main/java/org/greenplum/pxf/automation/components/cluster/installer/nodes/SegmentNode.java
> + * Represents a single StandBy Node in a cluster
```suggestion
 * Represents a single Segment Node in a cluster

2023-07-18 20:13 UTC, bradfordb-vmware requested changes

2023-07-18 20:13 UTC, bradfordb-vmware commented on cli/cmd/cluster.go
> +    connection := dbconn.NewDBConnFromEnvironment("postgres")
Do we need this method? The `DBConn` struct already has the `Version` field and we open a connection in `doSetup` and store the connection on the returned `ClusterData` struct. You can add a method `func (c *ClusterData) getHost string` that returns either `master` or `coordinator` whenever we need it.

2023-07-18 20:13 UTC, bradfordb-vmware commented on cli/cmd/cluster.go
> +	restartCmd  = createCobraCommand("restart", "Restart the PXF server on %s, standby master, and all segment hosts", &RestartCommand)
You also need to replace `standby master`.

2023-07-19 23:16 UTC, hpandeycodeit commented on cli/cmd/cluster.go
> +    connection := dbconn.NewDBConnFromEnvironment("postgres")
I have modified this function a bit as per recommendation but we also need `     connection := dbconn.NewDBConnFromEnvironment("postgres") ` as `clusterData` object isn't available to format `Short` in `createCobraCommand`

2023-07-20 18:17 UTC, yimingli-vmware commented on cli/cmd/cluster.go
> +		Short: fmt.Sprintf( short, hostName, hostName),
```suggestion
		Short: fmt.Sprintf(short, hostName, hostName),
```
why we have 2 `hostName` here?

2023-07-20 18:17 UTC, yimingli-vmware commented on cli/cmd/cluster.go
> +	migrateCmd  = createCobraCommand("migrate", "Migrates configurations from older installations of PXF %.s %.s", &MigrateCommand)
I think `hostName` would replace these `%s`, but why in this format it's not here?

2023-07-20 18:17 UTC, yimingli-vmware commented on concourse/scripts/cli/test_sync.sh
> +get_host_from_version="$(get_host_from_version)"
Maybe `hostName` would be a better name?

2023-07-20 18:17 UTC, yimingli-vmware commented on concourse/scripts/cli/common.sh
> +
extra line

2023-07-20 18:17 UTC, yimingli-vmware commented on concourse/scripts/cli/common.sh
> +  local cluster_description="$(get_host_from_version) host"
we use this function twice, let's create a variable and reuse it.

2023-07-21 00:00 UTC, bradfordb-vmware approved these changes

2023-07-21 22:32 UTC, hpandeycodeit commented on automation/src/main/java/org/greenplum/pxf/automation/components/cluster/installer/nodes/MasterNode.java
> -
This is renamed to Coordinator , so won't break anything.

2023-07-21 22:33 UTC, hpandeycodeit commented on cli/cmd/cluster.go
> +		Short: fmt.Sprintf( short, hostName, hostName),
This is changed. Not formatting this field not.

2023-07-21 22:33 UTC, hpandeycodeit commented on cli/cmd/cluster.go
> +	migrateCmd  = createCobraCommand("migrate", "Migrates configurations from older installations of PXF %.s %.s", &MigrateCommand)
This is changed, replaced master to coordinator.

2023-07-21 22:34 UTC, hpandeycodeit commented on concourse/scripts/cli/test_sync.sh
> +get_host_from_version="$(get_host_from_version)"
this is changed to original code.

2023-07-21 22:35 UTC, hpandeycodeit commented on concourse/scripts/cli/common.sh
> +
This is reverted to original code.

2023-07-21 22:35 UTC, hpandeycodeit commented on concourse/scripts/cli/common.sh
> +  local cluster_description="$(get_host_from_version) host"
This is reverted to original code.

2023-07-21 22:42 UTC, ashuka24 approved these changes

2023-07-24 17:14 UTC, merged